/**
 * completion-triggers.ts — Sprint 32+: final-invoice-paid → client lien waiver auto-generate.
 *
 * Architecture correction (Sprint 36): the Conditional Lien Waiver is signed by the
 * contractor (CHS), not the client. It is now auto-generated like the Warranty Certificate —
 * contractor signature embedded at generation time, stored in job_documents, no BoldSign send.
 *
 * checkAndFireLienWaiver() is invoked non-blocking after invoice payments settle.
 * All heavy work runs inside ctx.waitUntil().
 */

import type { Env } from "../env.js";
import { triggerNotification } from "./notification-engine.js";
import { round2 } from "./invoicing.js";
import { generateAndStoreDocument } from "../routes/job-documents.js";

async function runLienWaiverCheck(
  jobId: string,
  invoiceId: string,
  env: Env,
  skipNotifications = false,
): Promise<void> {
  try {
    const job = await env.DB.prepare(
      `SELECT id, status, contract_total, client_id FROM jobs WHERE id = ?`,
    )
      .bind(jobId)
      .first<{ id: string; status: string; contract_total: number; client_id: string }>();

    // Allow complete or closed — punch-list auto-complete may race with final payment.
    if (!job || !lienWaiverJobStatusAllowsGeneration(job.status)) return;

    // All non-void invoices must be paid
    const unpaid = await env.DB.prepare(
      `SELECT COUNT(*) as count FROM invoices
        WHERE job_id = ? AND status NOT IN ('paid', 'void')`,
    )
      .bind(jobId)
      .first<{ count: number }>();

    if (unpaid && unpaid.count > 0) return;

    // Exclude payments linked to voided invoices — they no longer count toward
    // "is this job fully paid". Orphaned payments (invoice_id IS NULL) still count.
    const financials = await env.DB.prepare(
      `SELECT COALESCE(SUM(p.amount), 0) as total_paid
         FROM payments p
         LEFT JOIN invoices i ON i.id = p.invoice_id
        WHERE p.job_id = ? AND (p.invoice_id IS NULL OR i.status != 'void')`,
    )
      .bind(jobId)
      .first<{ total_paid: number }>();

    const totalPaid = round2(financials?.total_paid ?? 0);
    const contractTotal = round2(job.contract_total ?? 0);
    if (totalPaid < contractTotal - 0.01) return;

    // Idempotency: stop if a non-discarded lien waiver already exists for this job
    const existingDoc = await env.DB.prepare(
      `SELECT id FROM job_documents
        WHERE job_id = ? AND template_type = 'lien_waiver_conditional'
          AND review_status IN (${LIEN_WAIVER_READY_REVIEW.map(() => "?").join(", ")})
        LIMIT 1`,
    )
      .bind(jobId, ...LIEN_WAIVER_READY_REVIEW)
      .first<{ id: string }>();

    if (existingDoc) {
      console.log(`[CompletionTrigger] Lien waiver already generated for job ${jobId}`);
      return;
    }

    // Gather data needed for the merge fields
    const invoice = await env.DB.prepare(`SELECT amount, paid_date FROM invoices WHERE id = ?`)
      .bind(invoiceId)
      .first<{ amount: number; paid_date: string | null }>();

    const today = new Date().toISOString().slice(0, 10);
    const paymentDate = invoice?.paid_date ?? today;
    const paymentAmount = String(invoice?.amount ?? 0);

    // Generate the lien waiver document (contractor signature embedded, signed immediately)
    const result = await generateAndStoreDocument(
      env,
      jobId,
      "lien_waiver_conditional",
      {
        payment_amount: paymentAmount,
        payment_date: paymentDate,
        through_date: paymentDate,
      },
      "system",
      {
        signImmediately: true,
        autoGenerated: true,
        triggerEvent: "client_payment",
        relatedRecordId: invoiceId,
      },
    );

    if (!skipNotifications) {
      await triggerNotification(env, "lien_waiver_generated", {
        jobId,
        clientId: job.client_id,
        linkPath: `/app/jobs/${jobId}/completion-package`,
        instanceKey: result.docId,
      });
    }

    console.log(`[CompletionTrigger] Lien waiver generated for job ${jobId}: doc ${result.docId}`);
  } catch (err) {
    const errMsg = err instanceof Error ? err.message : String(err);
    console.error(`[CompletionTrigger] Lien waiver generation failed for job ${jobId}:`, errMsg);
    try {
      await recordLienWaiverGenerationFailure(env, jobId, invoiceId, errMsg);
    } catch (persistErr) {
      console.error(
        `[CompletionTrigger] Failed to persist lien-waiver error for job ${jobId}:`,
        persistErr instanceof Error ? persistErr.message : persistErr,
      );
    }
  }
}

export const LIEN_WAIVER_READY_REVIEW = [
  "pending_review",
  "approved",
  "discarded",
  "manual",
] as const;

export const LIEN_WAIVER_FAILED_REVIEW = "failed";

export function lienWaiverJobStatusAllowsGeneration(status: string | null | undefined): boolean {
  return status === "complete" || status === "closed";
}

export async function recordLienWaiverGenerationFailure(
  env: Env,
  jobId: string,
  invoiceId: string | null,
  errMsg: string,
): Promise<void> {
  const existing = await env.DB.prepare(
    `SELECT id FROM job_documents
      WHERE job_id = ? AND template_type = 'lien_waiver_conditional' AND review_status = ?
      LIMIT 1`,
  )
    .bind(jobId, LIEN_WAIVER_FAILED_REVIEW)
    .first<{ id: string }>();
  if (existing) {
    await env.DB.prepare(
      `UPDATE job_documents SET notes = ?, related_record_id = ?, generated_at = datetime('now')
        WHERE id = ?`,
    )
      .bind(errMsg.slice(0, 2000), invoiceId, existing.id)
      .run();
    return;
  }
  await env.DB.prepare(
    `INSERT INTO job_documents
       (id, job_id, template_type, filename, r2_key, generated_at, generated_by,
        auto_generated, trigger_event, related_record_id, review_status, notes, signature_status)
     VALUES (?, ?, 'lien_waiver_conditional', 'lien-waiver-generation-failed', ?, datetime('now'),
             'system', 1, 'client_payment', ?, ?, ?, 'none')`,
  )
    .bind(
      crypto.randomUUID(),
      jobId,
      `documents/generated/${jobId}/lien-waiver-generation-failed`,
      invoiceId,
      LIEN_WAIVER_FAILED_REVIEW,
      errMsg.slice(0, 2000),
    )
    .run();
}

export async function checkAndFireLienWaiver({
  jobId,
  invoiceId,
  env,
  ctx,
  skipNotifications,
}: {
  jobId: string;
  invoiceId: string;
  env: Env;
  ctx?: ExecutionContext;
  /** Historical/external payments generate the waiver but never notify the client. */
  skipNotifications?: boolean;
}): Promise<void> {
  const run = () => runLienWaiverCheck(jobId, invoiceId, env, skipNotifications === true);
  if (ctx) {
    ctx.waitUntil(run());
  } else {
    await run();
  }
}

/** Fire lien-waiver check using the job's latest paid invoice (e.g. on job → complete). */
export async function checkAndFireLienWaiverForJob(
  env: Env,
  jobId: string,
  ctx?: ExecutionContext,
): Promise<void> {
  const inv = await env.DB.prepare(
    `SELECT id FROM invoices
      WHERE job_id = ? AND status = 'paid'
      ORDER BY datetime(COALESCE(paid_date, created_at)) DESC
      LIMIT 1`,
  )
    .bind(jobId)
    .first<{ id: string }>();
  if (!inv) return;
  await checkAndFireLienWaiver({ jobId, invoiceId: inv.id, env, ctx });
}
