/**
 * document-autotrigger.ts — Sprint 20: Auto-trigger document generation.
 *
 * maybeAutoGenerateDocument() is called non-blocking from event handlers
 * (job status change, payment insert, expense insert, change order approval).
 *
 * Contract:
 *  - NEVER throws. Returns { generated, reason? } on all paths.
 *  - Dedup guard: if a non-discarded row already exists with the same
 *    (job_id, template_type, related_record_id), returns { generated: false, reason: 'already_exists' }.
 *  - On any failure: inserts a dead_letter_queue row (operation='doc_autogen')
 *    and returns { generated: false, reason: 'error' }.
 */

import type { Env } from "../env.js";
import {
  resolveMergeFields,
  MissingFieldsError,
  TEMPLATE_R2_KEYS,
  type TemplateType,
  type JobRow,
} from "../routes/job-documents.js";
import { generateDocument } from "./document-generator.js";

export type TriggerEvent =
  | "job_deposit_paid"
  | "change_order_approved"
  | "client_payment"
  | "sub_payment"
  | "job_complete";

export interface AutoTriggerParams {
  jobId: string;
  templateType: TemplateType;
  triggerEvent: TriggerEvent;
  relatedRecordId?: string | null;
  overrides?: Record<string, string>;
}

export interface AutoTriggerResult {
  generated: boolean;
  reason?: string;
  docId?: string;
}

export async function maybeAutoGenerateDocument(
  env: Env,
  params: AutoTriggerParams,
): Promise<AutoTriggerResult> {
  const { jobId, templateType, triggerEvent, relatedRecordId = null, overrides = {} } = params;

  console.log(`[AUTOTRIGGER] maybeAutoGenerateDocument START — job=${jobId} type=${templateType} event=${triggerEvent}`);

  try {
    // 1. Dedup guard: block if any non-discarded... actually block on pending_review|approved|discarded
    //    (per business rule 6: discarded also blocks re-generation)
    const existing = await env.DB.prepare(
      `SELECT id FROM job_documents
        WHERE job_id = ?
          AND template_type = ?
          AND (
            (related_record_id IS NULL AND ? IS NULL)
            OR related_record_id = ?
          )
          AND review_status IN ('pending_review', 'approved', 'discarded')
        LIMIT 1`,
    )
      .bind(jobId, templateType, relatedRecordId, relatedRecordId)
      .first<{ id: string }>();

    if (existing) {
      console.log(`[AUTOTRIGGER] dedup hit — already exists id=${existing.id}`);
      return { generated: false, reason: "already_exists" };
    }

    // 2. Load job row
    const job = await env.DB.prepare(
      `SELECT id, job_number, title, client_id,
              property_address, property_city, property_state, property_zip,
              start_date, target_end_date, actual_end_date,
              contract_total, deposit_amount, notes, billing_model, warranty_expiration
         FROM jobs WHERE id = ?`,
    )
      .bind(jobId)
      .first<JobRow>();

    if (!job) {
      throw new Error(`job not found: ${jobId}`);
    }
    console.log(`[AUTOTRIGGER] job loaded — number=${job.job_number} client=${job.client_id}`);

    // 3. Resolve merge fields (reuse Sprint 19 resolver; caller provides required overrides)
    let mergeFields: Record<string, string>;
    try {
      mergeFields = await resolveMergeFields(env, job, overrides, templateType);
    } catch (e) {
      if (e instanceof MissingFieldsError) {
        throw new Error(`Missing required fields: ${e.missing.join(", ")}`);
      }
      throw e;
    }

    // 4. Fetch template from R2
    const r2Key = TEMPLATE_R2_KEYS[templateType];
    console.log(`[AUTOTRIGGER] fetching R2 template — key=${r2Key}`);
    const templateObj = await env.FILES.get(r2Key);
    if (!templateObj) {
      throw new Error(`template not found in R2: ${r2Key}`);
    }
    console.log(`[AUTOTRIGGER] R2 template found — size=${templateObj.size}`);
    const templateBuffer = await templateObj.arrayBuffer();

    // 5. Generate document
    const docBytes = await generateDocument(templateBuffer, mergeFields);

    // 6. Build filename and upload to R2
    const today = new Date().toISOString().slice(0, 10);
    const slugType = templateType.replace(/_/g, "-");
    const jobNum = (job.job_number ?? jobId).toString().replace(/\s+/g, "-");
    const filename = `${slugType}-${jobNum}-${today}.docx`;
    const generatedKey = `documents/generated/${jobId}/${filename}`;

    await env.FILES.put(generatedKey, docBytes, {
      httpMetadata: {
        contentType:
          "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
      },
    });

    // 7. Insert job_documents row with review_status='pending_review'
    const docId = crypto.randomUUID();
    await env.DB.prepare(
      `INSERT INTO job_documents
         (id, job_id, template_type, filename, r2_key, generated_at,
          generated_by, review_status, auto_generated, trigger_event, related_record_id)
       VALUES (?, ?, ?, ?, ?, datetime('now'), 'system', 'pending_review', 1, ?, ?)`,
    )
      .bind(docId, jobId, templateType, filename, generatedKey, triggerEvent, relatedRecordId)
      .run();

    console.log(`[AUTOTRIGGER] SUCCESS — docId=${docId} key=${generatedKey}`);
    return { generated: true, docId };
  } catch (err_) {
    // 8. DLQ: log failure, never re-throw to caller
    const errMsg = err_ instanceof Error ? err_.message : String(err_);
    console.error(`[AUTOTRIGGER] FAILED (${templateType}/${jobId}):`, errMsg);

    await env.DB.prepare(
      `INSERT INTO dead_letter_queue
         (id, operation, payload, error_message, retry_count, max_retries, status, created_at)
       VALUES (?, 'doc_autogen', ?, ?, 0, 3, 'pending', datetime('now'))`,
    )
      .bind(
        crypto.randomUUID(),
        JSON.stringify({ jobId, templateType, triggerEvent, relatedRecordId }),
        errMsg,
      )
      .run()
      .catch((dlqErr: unknown) => {
        console.error("[doc-autotrigger] DLQ insert also failed:", dlqErr);
      });

    return { generated: false, reason: "error" };
  }
}
