/**
 * document-autotrigger.ts — Sprint 20: Auto-trigger document generation.
 *
 * maybeAutoGenerateDocument() is called non-blocking from event handlers
 * (job status change, payment insert, expense insert, change order approval).
 *
 * Contract:
 *  - NEVER throws. Returns { generated, reason? } on all paths.
 *  - Dedup guard: if a non-discarded row already exists with the same
 *    (job_id, template_type, related_record_id), returns { generated: false, reason: 'already_exists' }.
 *  - On any failure: inserts a dead_letter_queue row (operation='doc_autogen')
 *    and returns { generated: false, reason: 'error' }.
 */

import type { Env } from "../env.js";
import {
  resolveMergeFields,
  MissingFieldsError,
  TEMPLATE_R2_KEYS,
  type TemplateType,
  type JobRow,
} from "../routes/job-documents.js";
import { generateDocument } from "./document-generator.js";
import { ensureServiceAgreementTemplate } from "./service-agreement-template.js";

export type TriggerEvent =
  | "job_deposit_paid"
  | "change_order_approved"
  | "client_payment"
  | "sub_payment"
  | "job_complete";

export interface AutoTriggerParams {
  jobId: string;
  templateType: TemplateType;
  triggerEvent: TriggerEvent;
  relatedRecordId?: string | null;
  overrides?: Record<string, string>;
}

export interface AutoTriggerResult {
  generated: boolean;
  reason?: string;
  docId?: string;
}

export async function maybeAutoGenerateDocument(
  env: Env,
  params: AutoTriggerParams,
): Promise<AutoTriggerResult> {
  const { jobId, templateType, triggerEvent, relatedRecordId = null, overrides = {} } = params;

  console.log(`[AUTOTRIGGER] maybeAutoGenerateDocument START — job=${jobId} type=${templateType} event=${triggerEvent}`);

  try {
    // 1. Dedup guard: block on pending_review|approved|discarded
    //    (per business rule 6: discarded also blocks re-generation).
    //    Once-per-job docs (lien waiver, warranty) ignore related_record_id so
    //    multiple payments cannot create duplicates.
    const oncePerJob =
      templateType === "lien_waiver_conditional" || templateType === "warranty_certificate";
    const existing = oncePerJob
      ? await env.DB.prepare(
          `SELECT id FROM job_documents
            WHERE job_id = ?
              AND template_type = ?
              AND review_status IN ('pending_review', 'approved', 'discarded')
            LIMIT 1`,
        )
          .bind(jobId, templateType)
          .first<{ id: string }>()
      : await env.DB.prepare(
          `SELECT id FROM job_documents
            WHERE job_id = ?
              AND template_type = ?
              AND (
                (related_record_id IS NULL AND ? IS NULL)
                OR related_record_id = ?
              )
              AND review_status IN ('pending_review', 'approved', 'discarded')
            LIMIT 1`,
        )
          .bind(jobId, templateType, relatedRecordId, relatedRecordId)
          .first<{ id: string }>();

    if (existing) {
      console.log(`[AUTOTRIGGER] dedup hit — already exists id=${existing.id}`);
      return { generated: false, reason: "already_exists" };
    }

    // 2. Load job row
    const job = await env.DB.prepare(
      `SELECT id, job_number, title, client_id,
              property_address, property_city, property_state, property_zip,
              start_date, target_end_date, actual_end_date,
              contract_total, deposit_amount, notes, billing_model, warranty_expiration,
              assigned_to
         FROM jobs WHERE id = ?`,
    )
      .bind(jobId)
      .first<JobRow>();

    if (!job) {
      throw new Error(`job not found: ${jobId}`);
    }
    console.log(`[AUTOTRIGGER] job loaded — number=${job.job_number} client=${job.client_id}`);

    // 3. Resolve merge fields (reuse Sprint 19 resolver; caller provides required overrides).
    // Change orders: fill portal typed-name approval fields from the CO row when missing.
    const enrichedOverrides = { ...overrides };
    if (templateType === "change_order" && relatedRecordId) {
      const co = await env.DB.prepare(
        `SELECT change_order_number, description, amount, client_signature, signed_name, approved_date
           FROM change_orders WHERE id = ?`,
      )
        .bind(relatedRecordId)
        .first<{
          change_order_number: number;
          description: string | null;
          amount: number;
          client_signature: string | null;
          signed_name: string | null;
          approved_date: string | null;
        }>();
      if (co) {
        const typedName = (co.signed_name || co.client_signature || "").trim();
        if (!enrichedOverrides.change_order_number) {
          enrichedOverrides.change_order_number = String(co.change_order_number ?? "");
        }
        if (!enrichedOverrides.change_description) {
          enrichedOverrides.change_description = co.description ?? "";
        }
        if (!enrichedOverrides.client_signature) {
          enrichedOverrides.client_signature = typedName;
        }
        if (!enrichedOverrides.client_approved_date && co.approved_date) {
          enrichedOverrides.client_approved_date = co.approved_date;
        }
        if (!enrichedOverrides.net_change) {
          enrichedOverrides.net_change = String(co.amount ?? 0);
        }
        if (!enrichedOverrides.revised_total) {
          enrichedOverrides.revised_total = String(job.contract_total ?? 0);
        }
        if (!enrichedOverrides.original_contract_amount) {
          enrichedOverrides.original_contract_amount = String(
            (job.contract_total ?? 0) - (co.amount ?? 0),
          );
        }
      }
    }

    let mergeFields: Record<string, string>;
    try {
      mergeFields = await resolveMergeFields(env, job, enrichedOverrides, templateType);
    } catch (e) {
      if (e instanceof MissingFieldsError) {
        throw new Error(`Missing required fields: ${e.missing.join(", ")}`);
      }
      throw e;
    }

    // 4. Fetch template from R2
    const r2Key = TEMPLATE_R2_KEYS[templateType];
    console.log(`[AUTOTRIGGER] fetching R2 template — key=${r2Key}`);
    const templateObj = await env.FILES.get(r2Key);
    if (!templateObj) {
      throw new Error(`template not found in R2: ${r2Key}`);
    }
    console.log(`[AUTOTRIGGER] R2 template found — size=${templateObj.size}`);
    let templateBuffer = await templateObj.arrayBuffer();
    if (templateType === "service_agreement") {
      templateBuffer = ensureServiceAgreementTemplate(templateBuffer);
    }

    // 5. Generate document — contractor signature for warranty + conditional lien waiver
    const contractorSigned =
      templateType === "warranty_certificate" || templateType === "lien_waiver_conditional";
    const docBytes = await generateDocument(templateBuffer, mergeFields, {
      embedContractorSignature: contractorSigned,
    });

    // 6. Build filename and upload to R2 — unique key so puts cannot collide with a stale object
    const today = new Date().toISOString().slice(0, 10);
    const slugType = templateType.replace(/_/g, "-");
    const jobNum = (job.job_number ?? jobId).toString().replace(/\s+/g, "-");
    const filename = `${slugType}-${jobNum}-${today}.docx`;
    const generatedKey = `documents/generated/${jobId}/${crypto.randomUUID()}-${filename}`;

    await env.FILES.put(generatedKey, docBytes, {
      httpMetadata: {
        contentType:
          "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
      },
    });
    const written = await env.FILES.head(generatedKey);
    if (!written || written.size !== docBytes.byteLength) {
      throw new Error(
        `r2_put_verify_failed: key=${generatedKey} expected=${docBytes.byteLength} got=${written?.size ?? "missing"}`,
      );
    }

    // 7. Insert job_documents row with review_status='pending_review'
    //    Contractor-signed docs mark signature_status=completed (no BoldSign send).
    const docId = crypto.randomUUID();
    const nowIso = new Date().toISOString().replace("T", " ").slice(0, 19);
    await env.DB.prepare(
      `INSERT INTO job_documents
         (id, job_id, template_type, filename, r2_key, generated_at,
          generated_by, review_status, auto_generated, trigger_event, related_record_id,
          signature_status, signature_completed_at)
       VALUES (?, ?, ?, ?, ?, datetime('now'), 'system', 'pending_review', 1, ?, ?, ?, ?)`,
    )
      .bind(
        docId,
        jobId,
        templateType,
        filename,
        generatedKey,
        triggerEvent,
        relatedRecordId,
        contractorSigned ? "completed" : "none",
        contractorSigned ? nowIso : null,
      )
      .run();

    console.log(`[AUTOTRIGGER] SUCCESS — docId=${docId} key=${generatedKey}`);
    return { generated: true, docId };
  } catch (err_) {
    // 8. DLQ: log failure, never re-throw to caller
    const errMsg = err_ instanceof Error ? err_.message : String(err_);
    console.error(`[AUTOTRIGGER] FAILED (${templateType}/${jobId}):`, errMsg);

    await env.DB.prepare(
      `INSERT INTO dead_letter_queue
         (id, operation, payload, error_message, retry_count, max_retries, status, created_at)
       VALUES (?, 'doc_autogen', ?, ?, 0, 3, 'pending', datetime('now'))`,
    )
      .bind(
        crypto.randomUUID(),
        JSON.stringify({ jobId, templateType, triggerEvent, relatedRecordId }),
        errMsg,
      )
      .run()
      .catch((dlqErr: unknown) => {
        console.error("[doc-autotrigger] DLQ insert also failed:", dlqErr);
      });

    return { generated: false, reason: "error" };
  }
}
