/**
 * Weekly liveness check for Vertex image generation.
 *
 * Folded into the existing nightly cron (`15 7 * * *`), Monday only — same
 * gate as weekly_photo_summary. No extra cron trigger. A success is silent.
 * A single failure is recorded and not announced. A second consecutive
 * Monday failure notifies the owner once (in-app bell via createOwnerInApp);
 * further failures in the same streak stay quiet until a success resets it.
 *
 * The generated bytes are discarded. Nothing is written to R2 and the
 * monthly image-gen counter is not bumped.
 */

import type { Env } from "../env.js";
import { createOwnerInApp } from "./notification-engine.js";
import { generateImageViaGemini, imageGenConfigured } from "./image-gen.js";
import { getSetting, SETTING_IMAGE_GEN_PROBE } from "./social.js";

export const IMAGE_GEN_PROBE_PROMPT = "a simple gray square, no text";

export interface ImageGenProbeState {
  status: "ok" | "fail" | "none";
  streak: number;
  notified: boolean;
}

export const EMPTY_PROBE_STATE: ImageGenProbeState = {
  status: "none",
  streak: 0,
  notified: false,
};

export function parseProbeState(raw: string | null | undefined): ImageGenProbeState {
  if (!raw) return { ...EMPTY_PROBE_STATE };
  try {
    const parsed = JSON.parse(raw) as Partial<ImageGenProbeState>;
    const status = parsed.status === "ok" || parsed.status === "fail" ? parsed.status : "none";
    return {
      status,
      streak: typeof parsed.streak === "number" && parsed.streak > 0 ? parsed.streak : 0,
      notified: parsed.notified === true,
    };
  } catch {
    return { ...EMPTY_PROBE_STATE };
  }
}

/**
 * First failure is silent. The next consecutive failure notifies once.
 * A success clears the streak so a later outage can notify again.
 */
export function decideImageGenProbe(
  prev: ImageGenProbeState,
  ok: boolean,
): { next: ImageGenProbeState; notify: boolean } {
  if (ok) {
    return { next: { status: "ok", streak: 0, notified: false }, notify: false };
  }
  const streak = prev.status === "fail" ? prev.streak + 1 : 1;
  const notify = streak >= 2 && !prev.notified;
  return {
    next: { status: "fail", streak, notified: prev.notified || notify },
    notify,
  };
}

async function readProbeState(env: Env): Promise<ImageGenProbeState> {
  return parseProbeState(await getSetting(env, SETTING_IMAGE_GEN_PROBE));
}

async function writeProbeState(env: Env, state: ImageGenProbeState): Promise<void> {
  await env.DB.prepare(
    `INSERT INTO system_settings (key, value, value_type, category, label, description, updated_at)
     VALUES (?, ?, 'json', 'social', 'Image generation probe', 'Weekly image-gen liveness streak. Not edited by hand.', datetime('now'))
     ON CONFLICT(key) DO UPDATE SET value = excluded.value, updated_at = datetime('now')`,
  )
    .bind(SETTING_IMAGE_GEN_PROBE, JSON.stringify(state))
    .run();
}

export interface ImageGenSelfTestResult {
  ran: boolean;
  ok?: boolean;
  notified?: boolean;
  error?: string | null;
}

/**
 * Monday-only liveness check. `now` is injectable so tests can force a Monday
 * without waiting on the clock. `generate` is injectable so a failure path
 * can be simulated without calling Vertex.
 */
export async function runImageGenSelfTest(
  env: Env,
  opts: {
    now?: Date;
    generate?: (env: Env) => Promise<void>;
  } = {},
): Promise<ImageGenSelfTestResult> {
  const now = opts.now ?? new Date();
  if (now.getDay() !== 1) return { ran: false };

  if (!(await imageGenConfigured(env))) return { ran: false };

  const generate =
    opts.generate ??
    (async (inner: Env) => {
      const { bytes } = await generateImageViaGemini(IMAGE_GEN_PROBE_PROMPT, inner);
      if (bytes.byteLength === 0) throw new Error("Empty image from Gemini");
      // Discard. This is a liveness check, not a stored generation.
    });

  let ok = false;
  let error: string | null = null;
  try {
    await generate(env);
    ok = true;
  } catch (err) {
    error = err instanceof Error ? err.message : String(err);
  }

  const prev = await readProbeState(env);
  const decision = decideImageGenProbe(prev, ok);
  await writeProbeState(env, decision.next);

  if (decision.notify) {
    const detail = (error ?? "unknown error").slice(0, 240);
    await createOwnerInApp(env, {
      message:
        `AI image generation is currently failing: ${detail}. ` +
        "Check the image model ID under Settings → Integrations.",
      linkPath: "/app/settings",
      dedupe: `image_gen_probe:${now.toISOString().slice(0, 10)}`,
      triggerEvent: "image_gen_probe",
    });
  }

  return { ran: true, ok, notified: decision.notify, error };
}
