/**
 * Review-highlight drafts. Auto path runs when the GBP sync inserts a new
 * 5-star row. The Reviews page can also create one for any rating.
 * No new cron — the auto path is inside the existing 30-minute sync tick.
 */

import type { Env } from "../env.js";
import { logSocialAudit } from "./social.js";
import {
  assembleHashtags,
  captionWithHeadline,
  fallbackHashtags,
  generateCaptions,
} from "./social-ai.js";

export interface ReviewForSocial {
  id: string;
  reviewer_name: string;
  comment_text: string | null;
  star_rating: number;
}

export function shouldAutoDraftReview(starRating: number): boolean {
  return starRating >= 5;
}

export async function createReviewHighlightPost(
  env: Env,
  review: ReviewForSocial,
  generatedBy: "ai_schedule" | "manual",
): Promise<{ id: string; created: boolean }> {
  if (generatedBy === "ai_schedule") {
    const existing = await env.DB.prepare(
      `SELECT id FROM social_posts
        WHERE post_type = 'review_highlight' AND engagement_data LIKE ?
        LIMIT 1`,
    )
      .bind(`%${review.id}%`)
      .first<{ id: string }>();
    if (existing) return { id: existing.id, created: false };
  }

  const detail = [review.reviewer_name, review.comment_text].filter(Boolean).join(" — ");
  const ctx = {
    kind: "review_highlight" as const,
    topic: `${review.star_rating}-star review from ${review.reviewer_name}`,
    detail: review.comment_text,
  };
  const captionRes = await generateCaptions(env, ctx);
  const body = captionRes.ok
    ? captionRes.options[0]!
    : `${review.reviewer_name} left a ${review.star_rating}-star review${
        review.comment_text ? `: “${review.comment_text.slice(0, 280)}”` : ""
      }. Free estimates — call us!`;
  const caption = captionWithHeadline(captionRes.headline, body);
  const hashtags = captionRes.ok
    ? assembleHashtags(null, captionRes.tradeTags, review.id)
    : fallbackHashtags(review.id);

  const id = crypto.randomUUID();
  await env.DB.prepare(
    `INSERT INTO social_posts
       (id, post_type, status, caption, hashtags, platform, scheduled_date,
        engagement_data, generated_by, created_at)
     VALUES (?, 'review_highlight', 'pending_approval', ?, ?, 'both', NULL, ?, ?, datetime('now'))`,
  )
    .bind(
      id,
      caption,
      JSON.stringify(hashtags),
      JSON.stringify({ google_review_id: review.id, source: detail.slice(0, 120) }),
      generatedBy,
    )
    .run();

  await logSocialAudit(env, "system", "social_post_autogenerated", id, {
    google_review_id: review.id,
    generated_by: generatedBy,
    star_rating: review.star_rating,
  });

  return { id, created: true };
}
