/**
 * Native Job Management API — Sprint 6 (CHS-API-Route-Map §Jobs, §Tasks).
 *
 * Jobs are NEVER created here: the only way a job exists is the shared
 * convertQuoteToJob() (manual Won modal + Stripe webhook). So there is no POST
 * /api/jobs. This module owns:
 *
 *   GET  /api/jobs                  list + filters (?status=&job_type=&client_id=&billing_model=)
 *   GET  /api/jobs/pipeline         jobs grouped by status (all 6 keys, empty arrays ok)
 *   GET  /api/jobs/:id              detail (overview + tasks + activity tabs)
 *   PUT  /api/jobs/:id              update editable fields (title, dates, notes)
 *   DELETE /api/jobs/:id            hard delete (closed/cancelled only; full cascade)
 *   PUT  /api/jobs/:id/status       dedicated status change (validates transitions, side effects)
 *   GET  /api/jobs/:id/tasks        tasks grouped by task_group, ordered
 *   POST /api/jobs/:id/tasks        create a task in a group
 *   PUT  /api/tasks/:id             update a task
 *   PUT  /api/tasks/:id/complete    mark complete (completed_date + completed_by)
 *
 * Native jobs are distinguished from legacy Jobber-synced rows by source =
 * 'estimate' (set by the conversion). The legacy Jobber jobs view lives at
 * /api/legacy/jobs (src/routes/jobs.ts) so this namespace is purely native.
 *
 * Conventions mirror estimate-requests.ts: thin handlers, parameterized D1,
 * audit logging on every write, role enforcement via guard().
 */

import type { Env } from "../env.js";
import { nativeJobSourceWhere, nativeJobSourceWhereAliased } from "../lib/native-jobs.js";
import { guard } from "../middleware/guard.js";
import { triggerJobStatusChanged } from "../lib/wc/triggers.js";
import { reverseJobConversion } from "../lib/quote-to-job.js";
import { maybeGenerateJobCompletionPost } from "../lib/social-jobs.js";
import { maybeAutoGenerateDocument } from "../lib/document-autotrigger.js";
import { checkAndFireLienWaiverForJob } from "../lib/completion-triggers.js";
import { shouldSkipContractAutogen } from "../lib/estimate-contract-document.js";
import { scheduleWorkingAgreementGeneration } from "../lib/working-agreement.js";
import { cascadeDeleteJob, DELETABLE_JOB_STATUSES } from "../lib/cascade-delete.js";
import { formatPmPhone, resolvePmFields } from "../lib/pm-fields.js";
import { generateWeeklyRecap } from "../lib/weekly-recap.js";
import { sendSubEmail } from "../lib/notification-engine.js";
import { invoiceLabel, warrantyExpirationDate } from "../lib/invoicing.js";
import {
  buildCostPlusFinalCycleCheck,
  buildFixedPriceFinalInvoiceCheck,
  type EligibilityCheck,
} from "../lib/close-eligibility.js";
import { NON_TEST_CLIENT } from "../lib/non-test-client.js";

const WRITE_ROLES = ["owner", "project_manager", "office_admin"] as const;
const REVERSE_ROLES = ["owner"] as const;

// Forward-only lifecycle (Job Management §2). Two backward exceptions only.
export const JOB_STATUSES = [
  "deposit_paid",
  "scheduled",
  "in_progress",
  "punch_list",
  "complete",
  "closed",
] as const;
type JobStatus = (typeof JOB_STATUSES)[number];

const STATUS_INDEX: Record<string, number> = Object.fromEntries(
  JOB_STATUSES.map((s, i) => [s, i]),
);

// Allowed backward moves (pause/weather; new punch items found).
const BACKWARD_EXCEPTIONS = new Set(["in_progress>scheduled", "complete>punch_list"]);

// ─── shared helpers (match estimate-requests.ts) ────────────────────────────

function json(body: unknown, init: ResponseInit = {}): Response {
  const headers = new Headers(init.headers);
  headers.set("content-type", "application/json; charset=utf-8");
  headers.set("cache-control", "no-store");
  return new Response(JSON.stringify(body), { ...init, headers });
}

function err(status: number, error: string, details?: string): Response {
  return json({ error, details }, { status });
}

async function readJson(request: Request): Promise<Record<string, unknown> | null> {
  try {
    return (await request.json()) as Record<string, unknown>;
  } catch {
    return null;
  }
}

function str(v: unknown): string | null {
  if (v === null || v === undefined) return null;
  const s = String(v).trim();
  return s === "" ? null : s;
}

async function logAudit(
  env: Env,
  userEmail: string,
  action: string,
  entityType: string,
  entityId: string,
  details: unknown,
): Promise<void> {
  await env.DB.prepare(
    "INSERT INTO audit_logs (id, user_email, action, entity_type, entity_id, details, created_at) VALUES (?, ?, ?, ?, ?, ?, datetime('now'))",
  )
    .bind(crypto.randomUUID(), userEmail, action, entityType, entityId, JSON.stringify(details))
    .run();
}

// ─── row shaping ────────────────────────────────────────────────────────────

interface JobListRow {
  id: string;
  job_number: number | null;
  title: string | null;
  status: string | null;
  client_id: string | null;
  client_name: string | null;
  billing_model: string | null;
  job_type: string | null;
  job_type_detail: string | null;
  lead_source: string | null;
  property_address: string | null;
  property_city: string | null;
  property_state: string | null;
  property_zip: string | null;
  contract_total: number | null;
  deposit_amount: number | null;
  deposit_paid: number | null;
  start_date: string | null;
  target_end_date: string | null;
  actual_end_date: string | null;
  warranty_expiration: string | null;
  portal_token: string | null;
  portal_type: string | null;
  conversion_complete: number | null;
  estimate_id: string | null;
  payer_id: string | null;
  source: string | null;
  created_at: string | null;
  updated_at: string | null;
  status_since: string | null; // last status-change timestamp (or created_at)
}

const NATIVE_JOB_WHERE = nativeJobSourceWhereAliased("j");

const JOB_SELECT = `
  SELECT j.id, j.job_number, j.title, j.status, j.client_id, c.name AS client_name,
         j.billing_model, j.job_type, j.job_type_detail, j.lead_source, j.source,
         j.property_address, j.property_city, j.property_state, j.property_zip,
         j.contract_total, j.deposit_amount, j.deposit_paid,
         j.start_date, j.target_end_date, j.actual_end_date, j.warranty_expiration,
         j.portal_token, j.portal_type, j.conversion_complete, j.estimate_id, j.payer_id,
         j.created_at, j.updated_at,
         COALESCE((
           SELECT MAX(a.created_at) FROM audit_logs a
           WHERE a.entity_type = 'job' AND a.entity_id = j.id
             AND a.action = 'job_status_changed'
         ), j.created_at) AS status_since
  FROM jobs j
  LEFT JOIN clients c ON c.id = j.client_id
  WHERE ${NATIVE_JOB_WHERE} AND (${NON_TEST_CLIENT})`;

function daysSince(iso: string | null): number {
  if (!iso) return 0;
  const then = new Date(iso).getTime();
  if (isNaN(then)) return 0;
  return Math.max(0, Math.floor((Date.now() - then) / 86_400_000));
}

function shapeJobCard(r: JobListRow) {
  const today = new Date().toISOString().slice(0, 10);
  const terminal = r.status === "complete" || r.status === "closed";
  const overdue = !!r.target_end_date && r.target_end_date < today && !terminal;
  return {
    id: r.id,
    job_number: r.job_number,
    job_display: r.job_number != null ? `JOB-${String(r.job_number).padStart(3, "0")}` : null,
    title: r.title,
    status: r.status,
    client_id: r.client_id,
    client_name: r.client_name,
    billing_model: r.billing_model,
    job_type: r.job_type,
    job_type_detail: r.job_type_detail ?? null,
    lead_source: r.lead_source,
    property_address: r.property_address,
    property_city: r.property_city,
    property_state: r.property_state,
    property_zip: r.property_zip,
    contract_total: r.contract_total,
    deposit_amount: r.deposit_amount,
    deposit_paid: (r.deposit_paid ?? 0) === 1,
    start_date: r.start_date,
    target_end_date: r.target_end_date,
    actual_end_date: r.actual_end_date,
    warranty_expiration: r.warranty_expiration,
    portal_token: r.portal_token,
    portal_type: r.portal_type,
    // The post-sale client portal view (/portal/:token) is later-sprint work and
    // has no route yet, so we surface no link. portal_token stays on the row
    // (selected above) for that future portal; we just don't advertise a path.
    portal_path: null,
    conversion_complete: (r.conversion_complete ?? 0) === 1,
    estimate_id: r.estimate_id,
    payer_id: r.payer_id,
    source: r.source,
    days_in_status: daysSince(r.status_since),
    photo_count: 0, // stub until Sprint 8
    overdue,
    created_at: r.created_at,
    updated_at: r.updated_at,
  };
}

// ─── GET /api/jobs ──────────────────────────────────────────────────────────

export async function handleJobList(env: Env, url: URL): Promise<Response> {
  const status = url.searchParams.get("status");
  const jobType = url.searchParams.get("job_type");
  const clientId = url.searchParams.get("client_id");
  const billingModel = url.searchParams.get("billing_model");

  const where: string[] = [];
  const binds: unknown[] = [];
  if (status) {
    where.push("j.status = ?");
    binds.push(status);
  }
  if (jobType) {
    where.push("j.job_type = ?");
    binds.push(jobType);
  }
  if (clientId) {
    where.push("j.client_id = ?");
    binds.push(clientId);
  }
  if (billingModel) {
    where.push("j.billing_model = ?");
    binds.push(billingModel);
  }

  const sql = `${JOB_SELECT}${where.length ? " AND " + where.join(" AND ") : ""} ORDER BY j.created_at DESC`;
  const rows = (await env.DB.prepare(sql).bind(...binds).all<JobListRow>()).results ?? [];

  return json({ as_of: new Date().toISOString(), total: rows.length, jobs: rows.map(shapeJobCard) });
}

// ─── GET /api/jobs/pipeline ───────────────────────────────────────────────────

export async function handleJobPipeline(env: Env): Promise<Response> {
  const rows = (await env.DB.prepare(`${JOB_SELECT} ORDER BY j.created_at DESC`).all<JobListRow>())
    .results ?? [];
  const cards = rows.map(shapeJobCard);

  const pipeline: Record<string, ReturnType<typeof shapeJobCard>[]> = {};
  const counts: Record<string, number> = {};
  for (const s of JOB_STATUSES) {
    pipeline[s] = [];
    counts[s] = 0;
  }
  for (const card of cards) {
    const s = String(card.status ?? "");
    if (s in pipeline) {
      pipeline[s].push(card);
      counts[s]++;
    }
  }

  return json({
    as_of: new Date().toISOString(),
    statuses: JOB_STATUSES,
    counts,
    pipeline,
  });
}

// ─── GET /api/jobs/:id ────────────────────────────────────────────────────────

export async function handleJobDetail(env: Env, id: string): Promise<Response> {
  const row = await env.DB.prepare(
    `${JOB_SELECT.replace(
      `WHERE ${NATIVE_JOB_WHERE} AND (${NON_TEST_CLIENT})`,
      `WHERE j.id = ? AND ${NATIVE_JOB_WHERE}`,
    )}`,
  )
    .bind(id)
    .first<JobListRow & { client_name: string | null }>();
  if (!row) return err(404, "not_found", "Job not found.");

  // Client contact (for the Overview tab).
  const client = row.client_id
    ? await env.DB.prepare(
        "SELECT name, first_name, last_name, phone, email FROM clients WHERE id = ?",
      )
        .bind(row.client_id)
        .first<{
          name: string | null;
          first_name: string | null;
          last_name: string | null;
          phone: string | null;
          email: string | null;
        }>()
    : null;

  // Deposit paid to date (fee-excluded contract-applicable amount per decision (b)).
  const depositRow = await env.DB.prepare(
    "SELECT COALESCE(SUM(amount), 0) AS paid FROM payments WHERE job_id = ?",
  )
    .bind(id)
    .first<{ paid: number }>();

  const tasks = await loadTasksGrouped(env, id, null, null);
  const billing = (
    await env.DB.prepare(
      "SELECT id, billing_model, sequence, label, trigger_type, trigger_ref, percentage, amount, period_start, period_end, status FROM billing_schedule WHERE job_id = ? ORDER BY sequence ASC",
    )
      .bind(id)
      .all<Record<string, unknown>>()
  ).results ?? [];

  const activity = (
    await env.DB.prepare(
      `SELECT id, user_email, action, details, created_at FROM audit_logs
       WHERE entity_type = 'job' AND entity_id = ?
       ORDER BY created_at DESC LIMIT 100`,
    )
      .bind(id)
      .all<Record<string, unknown>>()
  ).results ?? [];

  const card = shapeJobCard(row);
  const clientName =
    [client?.first_name, client?.last_name].filter(Boolean).join(" ").trim() ||
    client?.name ||
    card.client_name;

  // Surface conversion_reversed (Sprint 12).
  const reversal = await env.DB.prepare(
    "SELECT conversion_reversed, reversal_reason, reversed_at FROM jobs WHERE id = ?",
  )
    .bind(id)
    .first<{
      conversion_reversed: number | null;
      reversal_reason: string | null;
      reversed_at: string | null;
    }>();
  const origin = (env.APP_PUBLIC_ORIGIN ?? "https://client.homesolutionsar.com").replace(/\/$/, "");
  const portalUrl = card.portal_token ? `${origin}/portal/${card.portal_token}` : null;

  let payer: {
    id: string;
    company_name: string | null;
    contact_name: string;
    email: string;
    card_brand: string | null;
    card_last4: string | null;
    has_card_on_file: boolean;
  } | null = null;
  if (row.payer_id) {
    payer = await env.DB.prepare(
      `SELECT id, company_name, contact_name, email, card_brand, card_last4, stripe_payment_method_id
         FROM payers WHERE id = ?`,
    )
      .bind(row.payer_id)
      .first<{
        id: string;
        company_name: string | null;
        contact_name: string;
        email: string;
        card_brand: string | null;
        card_last4: string | null;
        stripe_payment_method_id: string | null;
      }>()
      .then((p) =>
        p
          ? {
              id: p.id,
              company_name: p.company_name,
              contact_name: p.contact_name,
              email: p.email,
              card_brand: p.card_brand,
              card_last4: p.card_last4,
              has_card_on_file: !!p.stripe_payment_method_id,
            }
          : null,
      );
  }

  const assignmentRow = await env.DB.prepare("SELECT assigned_to FROM jobs WHERE id = ?")
    .bind(id)
    .first<{ assigned_to: string | null }>();
  const assignedTo = assignmentRow?.assigned_to ?? null;
  let assigned_to_name: string | null = null;
  let assigned_to_phone: string | null = null;
  let assigned_to_email: string | null = null;
  if (assignedTo) {
    const pmUser = await env.DB.prepare(
      "SELECT first_name, last_name, name, business_phone, email FROM users WHERE id = ?",
    )
      .bind(assignedTo)
      .first<{
        first_name: string | null;
        last_name: string | null;
        name: string | null;
        business_phone: string | null;
        email: string | null;
      }>();
    if (pmUser) {
      assigned_to_name =
        [pmUser.first_name, pmUser.last_name].filter(Boolean).join(" ").trim() ||
        (pmUser.name ?? "").trim() ||
        null;
      assigned_to_phone = formatPmPhone(pmUser.business_phone);
      assigned_to_email = pmUser.email?.trim() || null;
    } else {
      const pm = await resolvePmFields(env, null);
      assigned_to_name = pm.pm_name;
      assigned_to_phone = pm.pm_phone;
      assigned_to_email = pm.pm_email;
    }
  }

  return json({
    job: {
      ...card,
      assigned_to: assignedTo,
      assigned_to_name,
      assigned_to_phone,
      assigned_to_email,
      client_name: clientName,
      client_phone: client?.phone ?? null,
      client_email: client?.email ?? null,
      payer,
      conversion_reversed: (reversal?.conversion_reversed ?? 0) === 1,
      reversal_reason: reversal?.reversal_reason ?? null,
      reversed_at: reversal?.reversed_at ?? null,
      portal_url: portalUrl,
    },
    financial: {
      contract_total: card.contract_total,
      deposit_amount: card.deposit_amount,
      deposit_paid_to_date: round2(depositRow?.paid ?? 0),
    },
    task_groups: tasks,
    billing_schedule: billing,
    activity,
  });
}

// ─── PUT /api/jobs/:id ────────────────────────────────────────────────────────

export async function handleJobUpdate(request: Request, env: Env, id: string): Promise<Response> {
  const guarded = await guard(request, env, [...WRITE_ROLES]);
  if (guarded instanceof Response) return guarded;
  const { user } = guarded;

  const body = await readJson(request);
  if (!body) return err(400, "bad_request", "Body must be JSON");

  if ("status" in body) {
    return err(
      400,
      "use_status_endpoint",
      "Status changes go through PUT /api/jobs/:id/status, which validates transitions.",
    );
  }

  const job = await env.DB.prepare(
    `SELECT id FROM jobs WHERE id = ? AND ${nativeJobSourceWhere()}`,
  )
    .bind(id)
    .first<{ id: string }>();
  if (!job) return err(404, "not_found", "Job not found.");

  const sets: string[] = [];
  const binds: unknown[] = [];

  if ("assigned_to" in body) {
    const raw = body.assigned_to;
    const assignedTo =
      raw === null || raw === undefined || raw === "" ? null : str(raw);
    if (assignedTo) {
      const userOk = await env.DB.prepare(
        "SELECT id FROM users WHERE id = ? AND is_active = 1",
      )
        .bind(assignedTo)
        .first<{ id: string }>();
      if (!userOk) {
        return err(400, "invalid_user", "Assigned user not found or inactive.");
      }
    }
    sets.push("assigned_to = ?");
    binds.push(assignedTo);
  }

  const editable: Record<string, "str"> = {
    title: "str",
    notes: "str",
    start_date: "str",
    target_end_date: "str",
    actual_end_date: "str",
    payer_id: "str",
  };
  for (const [field] of Object.entries(editable)) {
    if (field in body) {
      sets.push(`${field} = ?`);
      binds.push(str(body[field]));
    }
  }

  // Boolean toggle fields (0/1).
  if ("review_enabled" in body) {
    sets.push("review_enabled = ?");
    binds.push(body.review_enabled ? 1 : 0);
  }

  if (sets.length === 0) return err(400, "bad_request", "No editable fields provided.");

  sets.push("updated_at = ?");
  binds.push(new Date().toISOString());
  binds.push(id);

  await env.DB.prepare(`UPDATE jobs SET ${sets.join(", ")} WHERE id = ?`).bind(...binds).run();
  await logAudit(env, user.email, "job_updated", "job", id, {
    fields: [
      ...Object.keys(editable).filter((f) => f in body),
      ...("assigned_to" in body ? ["assigned_to"] : []),
      ...("review_enabled" in body ? ["review_enabled"] : []),
    ],
  });

  return handleJobDetail(env, id);
}

// ─── PUT /api/jobs/:id/review-received ────────────────────────────────────────

/**
 * Idempotent — marks review_received = 1 and stamps review_received_at.
 * Stops the follow-up sequence for this job on the next nightly sweep.
 * Auth: O/PM.
 */
export async function handleJobReviewReceived(request: Request, env: Env, id: string): Promise<Response> {
  const guarded = await guard(request, env, ["owner", "project_manager"] as const);
  if (guarded instanceof Response) return guarded;
  const { user } = guarded;

  const job = await env.DB.prepare(
    "SELECT id, review_received FROM jobs WHERE id = ?",
  ).bind(id).first<{ id: string; review_received: number }>();
  if (!job) return err(404, "not_found", "Job not found.");

  if (job.review_received) {
    return json({ ok: true, review_received: true, review_received_at: null, already_set: true });
  }

  await env.DB.prepare(
    `UPDATE jobs SET review_received = 1, review_received_at = datetime('now'), updated_at = ? WHERE id = ?`,
  ).bind(new Date().toISOString(), id).run();

  await logAudit(env, user.email, "job_review_received", "job", id, {});

  return json({ ok: true, review_received: true });
}

// ─── Close-eligibility check (shared by GET and gate inside PUT /status) ─────

interface EligibilityResult {
  eligible: boolean;
  checks: EligibilityCheck[];
}

async function computeCloseEligibility(env: Env, jobId: string): Promise<EligibilityResult> {
  const checks: EligibilityCheck[] = [];

  const jobRow = await env.DB.prepare(`SELECT billing_model FROM jobs WHERE id = ?`)
    .bind(jobId)
    .first<{ billing_model: string | null }>();
  const billingModel = (jobRow?.billing_model ?? "fixed_price").toLowerCase();

  // 1. invoices_paid — every non-void, non-draft invoice must be paid.
  const unpaidRows = (
    await env.DB.prepare(
      `SELECT invoice_number
         FROM invoices
        WHERE job_id = ?
          AND status NOT IN ('void', 'draft', 'paid')`,
    )
      .bind(jobId)
      .all<{ invoice_number: number | null }>()
  ).results ?? [];
  const unpaidLabels = unpaidRows.map((r) => invoiceLabel(r.invoice_number));
  checks.push({
    id: "invoices_paid",
    label: "All invoices paid",
    passed: unpaidRows.length === 0,
    detail:
      unpaidRows.length > 0
        ? `${unpaidRows.length} invoice(s) unpaid: ${unpaidLabels.join(", ")}`
        : null,
  });

  // 2. no_draft_invoices — no draft or sent (unresolved) invoices.
  const draftRow = await env.DB.prepare(
    `SELECT COUNT(*) AS n FROM invoices WHERE job_id = ? AND status IN ('draft', 'sent')`,
  )
    .bind(jobId)
    .first<{ n: number }>();
  checks.push({
    id: "no_draft_invoices",
    label: "No draft/unsent invoices",
    passed: (draftRow?.n ?? 0) === 0,
    detail: (draftRow?.n ?? 0) > 0 ? `${draftRow!.n} draft/sent invoice(s) not yet resolved` : null,
  });

  // 3. expenses_logged — at least one expense record exists.
  const expRow = await env.DB.prepare(
    `SELECT COUNT(*) AS n FROM expenses WHERE job_id = ?`,
  )
    .bind(jobId)
    .first<{ n: number }>();
  checks.push({
    id: "expenses_logged",
    label: "Expenses logged for job",
    passed: (expRow?.n ?? 0) > 0,
    detail: (expRow?.n ?? 0) === 0 ? "No expense records found — unusual for a real job" : null,
  });

  // 4. no_open_co — no change orders in draft or sent status.
  const coRow = await env.DB.prepare(
    `SELECT COUNT(*) AS n FROM change_orders WHERE job_id = ? AND status IN ('draft', 'sent')`,
  )
    .bind(jobId)
    .first<{ n: number }>();
  checks.push({
    id: "no_open_co",
    label: "No open change orders",
    passed: (coRow?.n ?? 0) === 0,
    detail: (coRow?.n ?? 0) > 0 ? `${coRow!.n} change order(s) awaiting signature or approval` : null,
  });

  // 5. punch_list_clear — no open punch-list tasks.
  const plRow = await env.DB.prepare(
    `SELECT COUNT(*) AS n FROM tasks WHERE job_id = ? AND is_punch_list = 1 AND status NOT IN ('complete', 'skipped')`,
  )
    .bind(jobId)
    .first<{ n: number }>();
  checks.push({
    id: "punch_list_clear",
    label: "Punch list complete",
    passed: (plRow?.n ?? 0) === 0,
    detail: (plRow?.n ?? 0) > 0 ? `${plRow!.n} open punch list item(s) remaining` : null,
  });

  // 6. Completion signal — billing-model specific.
  if (billingModel === "cost_plus") {
    const finalCycle = await env.DB.prepare(
      `SELECT id, status, invoice_id, reconciliation_invoice_id, reconciliation_date, cycle_number
         FROM billing_cycles
        WHERE job_id = ? AND is_final_cycle = 1
        ORDER BY cycle_number DESC
        LIMIT 1`,
    )
      .bind(jobId)
      .first<{
        id: string;
        status: string;
        invoice_id: string | null;
        reconciliation_invoice_id: string | null;
        reconciliation_date: string | null;
        cycle_number: number;
      }>();

    const invoiceIds = [finalCycle?.invoice_id, finalCycle?.reconciliation_invoice_id].filter(
      (id): id is string => !!id,
    );
    const cycleInvoices =
      invoiceIds.length > 0
        ? ((
            await env.DB.prepare(
              `SELECT id, invoice_number, status FROM invoices WHERE id IN (${invoiceIds.map(() => "?").join(", ")})`,
            )
              .bind(...invoiceIds)
              .all<{ id: string; invoice_number: number | null; status: string }>()
          ).results ?? [])
        : [];

    checks.push(buildCostPlusFinalCycleCheck(finalCycle ?? null, cycleInvoices));
  } else {
    const finalRow = await env.DB.prepare(
      `SELECT invoice_number, status FROM invoices WHERE job_id = ? AND invoice_type = 'final' ORDER BY created_at DESC LIMIT 1`,
    )
      .bind(jobId)
      .first<{ invoice_number: number | null; status: string }>();
    checks.push(buildFixedPriceFinalInvoiceCheck(finalRow ?? null));
  }

  return { eligible: checks.every((c) => c.passed), checks };
}

// ─── GET /api/jobs/:id/close-eligibility ─────────────────────────────────────

export async function handleJobCloseEligibility(request: Request, env: Env, id: string): Promise<Response> {
  const guarded = await guard(request, env, [...WRITE_ROLES]);
  if (guarded instanceof Response) return guarded;

  const job = await env.DB.prepare(`SELECT id FROM jobs WHERE id = ? AND ${nativeJobSourceWhere()}`)
    .bind(id)
    .first<{ id: string }>();
  if (!job) return err(404, "not_found", "Job not found.");

  const result = await computeCloseEligibility(env, id);
  return json(result);
}

// ─── PUT /api/jobs/:id/status ─────────────────────────────────────────────────

export async function handleJobStatus(request: Request, env: Env, id: string, ctx: ExecutionContext): Promise<Response> {
  const guarded = await guard(request, env, [...WRITE_ROLES]);
  if (guarded instanceof Response) return guarded;
  const { user } = guarded;

  const body = await readJson(request);
  if (!body) return err(400, "bad_request", "Body must be JSON");
  const target = str(body.status);
  if (!target || !(target in STATUS_INDEX)) {
    return err(400, "bad_request", `status must be one of: ${JOB_STATUSES.join(", ")}`);
  }

  const job = await env.DB.prepare(
    `SELECT id, status FROM jobs WHERE id = ? AND ${nativeJobSourceWhere()}`,
  )
    .bind(id)
    .first<{ id: string; status: string }>();
  if (!job) return err(404, "not_found", "Job not found.");

  const from = job.status;
  if (from === target) return err(400, "no_change", "Job is already in that status.");

  const fromIdx = STATUS_INDEX[from] ?? -1;
  const toIdx = STATUS_INDEX[target];
  const isForward = fromIdx >= 0 && toIdx > fromIdx;
  const isAllowedBackward = BACKWARD_EXCEPTIONS.has(`${from}>${target}`);
  if (!isForward && !isAllowedBackward) {
    return err(
      400,
      "illegal_transition",
      `Cannot move from ${from} to ${target}. Jobs move forward only (allowed backward: in_progress→scheduled, complete→punch_list).`,
    );
  }

  // Gate → complete: all punch-list items must be complete (§6.9).
  if (target === "complete") {
    const open = await env.DB.prepare(
      "SELECT COUNT(*) AS n FROM tasks WHERE job_id = ? AND is_punch_list = 1 AND status != 'complete'",
    )
      .bind(id)
      .first<{ n: number }>();
    if ((open?.n ?? 0) > 0) {
      return err(
        409,
        "open_punch_list",
        `Cannot complete: ${open!.n} punch-list item(s) still open.`,
      );
    }
  }

  // Gate → closed: full 6-check reconciliation (Sprint 25 §D1B).
  // Returns 422 with structured checks array so the frontend can display exactly
  // what is blocking closure. Backend is authoritative — the frontend gate is UX polish.
  if (target === "closed") {
    const eligibility = await computeCloseEligibility(env, id);
    if (!eligibility.eligible) {
      return json({ error: "Job cannot be closed", checks: eligibility.checks }, { status: 422 });
    }
  }

  const nowIso = new Date().toISOString();
  // actual_end_date is stamped when the job first reaches complete.
  const setActualEnd = target === "complete";
  if (target === "closed") {
    const dates = await env.DB.prepare("SELECT actual_end_date FROM jobs WHERE id = ?")
      .bind(id)
      .first<{ actual_end_date: string | null }>();
    const completionDate = dates?.actual_end_date?.slice(0, 10) ?? nowIso.slice(0, 10);
    const warrantyExp = warrantyExpirationDate(completionDate);
    await env.DB.prepare(
      `UPDATE jobs
          SET status = ?, updated_at = ?, warranty_expiration = ?,
              actual_end_date = COALESCE(actual_end_date, ?)
        WHERE id = ?`,
    )
      .bind(target, nowIso, warrantyExp, completionDate, id)
      .run();
  } else {
    await env.DB.prepare(
      `UPDATE jobs SET status = ?, updated_at = ?${setActualEnd ? ", actual_end_date = COALESCE(actual_end_date, ?)" : ""} WHERE id = ?`,
    )
      .bind(...(setActualEnd ? [target, nowIso, nowIso.slice(0, 10), id] : [target, nowIso, id]))
      .run();
  }

  await logAudit(env, user.email, "job_status_changed", "job", id, { from, to: target });
  triggerJobStatusChanged(env, id, from, target);

  // Sprint 16 — Social Media auto-gen seam. On reaching `complete`, draft a
  // pending_approval job-completion post if the job has social-ready photos
  // (else notify "flag photos?"). NEVER auto-publishes; non-fatal so a social
  // hiccup can't block the status change.
  if (target === "complete") {
    await maybeGenerateJobCompletionPost(env, id, user.email).catch((e) =>
      console.error("[jobs-api] social auto-gen failed:", (e as Error).message),
    );
  }

  // Sprint 20 — Auto-generate contract document on deposit_paid; warranty cert on complete.
  // Non-blocking: doc gen failure must never roll back the status change.
  if (target === "deposit_paid") {
    // Determine contract template from billing_model
    const jobForBilling = await env.DB.prepare(
      "SELECT billing_model FROM jobs WHERE id = ?",
    )
      .bind(id)
      .first<{ billing_model: string | null }>();
    const billingModel = jobForBilling?.billing_model ?? "fixed_price";
    const contractTemplate =
      billingModel === "cost_plus" ? "cost_plus_agreement" : "service_agreement";
    // NOTE: trade_by_trade → service_agreement (confirmed default; flag for Tony in report-back)
    const skipAutogen = await shouldSkipContractAutogen(env, id, contractTemplate);
    if (skipAutogen) {
      console.log(
        `[AUTOTRIGGER] jobs-api deposit_paid — skip ${contractTemplate} (estimate contract already signed)`,
      );
    } else {
      console.log(`[AUTOTRIGGER] jobs-api deposit_paid — jobId=${id} template=${contractTemplate}`);
      ctx.waitUntil(
        maybeAutoGenerateDocument(env, {
          jobId: id,
          templateType: contractTemplate,
          triggerEvent: "job_deposit_paid",
        }).catch((e) =>
          console.error("[jobs-api] doc auto-gen (deposit_paid) failed:", (e as Error).message),
        ),
      );
    }
    scheduleWorkingAgreementGeneration(env, id, ctx);
  }

  if (target === "complete") {
    console.log(`[AUTOTRIGGER] jobs-api complete — jobId=${id}`);
    ctx.waitUntil(
      (async () => {
        await maybeAutoGenerateDocument(env, {
          jobId: id,
          templateType: "warranty_certificate",
          triggerEvent: "job_complete",
        });
        // Companion fancy visual warranty (same trigger; does not replace the personalized cert).
        const { maybeAutoGenerateFancyWarranty } = await import("../lib/warranty-fancy.js");
        await maybeAutoGenerateFancyWarranty(env, id, "job_complete");
        // If final payment already settled before complete, generate the lien waiver now.
        await checkAndFireLienWaiverForJob(env, id);
      })().catch((e) =>
        console.error("[jobs-api] doc auto-gen (complete) failed:", (e as Error).message),
      ),
    );
  }

  return handleJobDetail(env, id);
}

/**
 * Reverse a job conversion (un-win) — owner only. The manual counterpart to the
 * Stripe refund/dispute webhook branch; both call the SAME reverseJobConversion()
 * (src/lib/quote-to-job.ts), which FLAGS-AND-PRESERVES: the job is kept and
 * flagged, its open invoices are voided (preserved), payments are untouched.
 */
export async function handleJobReverseConversion(request: Request, env: Env, id: string): Promise<Response> {
  const guarded = await guard(request, env, [...REVERSE_ROLES]);
  if (guarded instanceof Response) return guarded;
  const { user } = guarded;

  const body = await readJson(request);
  const reason = (body ? str(body.reason) : null) ?? "manual_reversal";

  const outcome = await reverseJobConversion(env, id, reason, user.email);
  if (!outcome.ok) return err(outcome.status, outcome.error, outcome.details);

  return handleJobDetail(env, id);
}

// ─── Tasks ────────────────────────────────────────────────────────────────────

interface TaskRow {
  id: string;
  job_id: string;
  task_group: string;
  task_group_order: number;
  title: string;
  status: string;
  assigned_to: string | null;
  scheduled_date: string | null;
  completed_date: string | null;
  completed_by: string | null;
  notes: string | null;
  sort_order: number;
  is_punch_list: number | null;
  created_at: string | null;
}

function shapeTask(r: TaskRow) {
  return {
    id: r.id,
    job_id: r.job_id,
    task_group: r.task_group,
    task_group_order: r.task_group_order,
    title: r.title,
    status: r.status,
    assigned_to: r.assigned_to,
    scheduled_date: r.scheduled_date,
    completed_date: r.completed_date,
    completed_by: r.completed_by,
    notes: r.notes,
    sort_order: r.sort_order,
    is_punch_list: (r.is_punch_list ?? 0) === 1,
    created_at: r.created_at,
  };
}

/** Tasks grouped by task_group, ordered by task_group_order then sort_order. */
async function loadTasksGrouped(
  env: Env,
  jobId: string,
  status: string | null,
  taskGroup: string | null,
): Promise<{ group: string; group_order: number; tasks: ReturnType<typeof shapeTask>[] }[]> {
  const where = ["job_id = ?"];
  const binds: unknown[] = [jobId];
  if (status) {
    where.push("status = ?");
    binds.push(status);
  }
  if (taskGroup) {
    where.push("task_group = ?");
    binds.push(taskGroup);
  }
  const rows =
    (
      await env.DB.prepare(
        `SELECT * FROM tasks WHERE ${where.join(" AND ")} ORDER BY task_group_order ASC, sort_order ASC, created_at ASC`,
      )
        .bind(...binds)
        .all<TaskRow>()
    ).results ?? [];

  const groups = new Map<string, { group: string; group_order: number; tasks: ReturnType<typeof shapeTask>[] }>();
  for (const r of rows) {
    let g = groups.get(r.task_group);
    if (!g) {
      g = { group: r.task_group, group_order: r.task_group_order, tasks: [] };
      groups.set(r.task_group, g);
    }
    g.tasks.push(shapeTask(r));
  }
  return [...groups.values()].sort((a, b) => a.group_order - b.group_order);
}

export async function handleTaskList(env: Env, jobId: string, url: URL): Promise<Response> {
  const job = await env.DB.prepare("SELECT id FROM jobs WHERE id = ?").bind(jobId).first<{ id: string }>();
  if (!job) return err(404, "not_found", "Job not found.");
  const groups = await loadTasksGrouped(
    env,
    jobId,
    url.searchParams.get("status"),
    url.searchParams.get("task_group"),
  );
  return json({ job_id: jobId, task_groups: groups });
}

export async function handleTaskCreate(request: Request, env: Env, jobId: string): Promise<Response> {
  const guarded = await guard(request, env, [...WRITE_ROLES]);
  if (guarded instanceof Response) return guarded;
  const { user } = guarded;

  const job = await env.DB.prepare("SELECT id FROM jobs WHERE id = ?").bind(jobId).first<{ id: string }>();
  if (!job) return err(404, "not_found", "Job not found.");

  const body = await readJson(request);
  if (!body) return err(400, "bad_request", "Body must be JSON");
  const title = str(body.title);
  const taskGroup = str(body.task_group);
  if (!title || !taskGroup) return err(400, "bad_request", "title and task_group are required.");

  // New group inherits the next group_order; existing group reuses its order.
  const existing = await env.DB.prepare(
    "SELECT task_group_order FROM tasks WHERE job_id = ? AND task_group = ? LIMIT 1",
  )
    .bind(jobId, taskGroup)
    .first<{ task_group_order: number }>();
  let groupOrder: number;
  if (existing) {
    groupOrder = existing.task_group_order;
  } else {
    const maxRow = await env.DB.prepare(
      "SELECT COALESCE(MAX(task_group_order), -1) AS m FROM tasks WHERE job_id = ?",
    )
      .bind(jobId)
      .first<{ m: number }>();
    groupOrder = (maxRow?.m ?? -1) + 1;
  }

  const sortOrder =
    body.sort_order != null && Number.isFinite(Number(body.sort_order))
      ? Number(body.sort_order)
      : await nextSortOrder(env, jobId, taskGroup);

  const id = crypto.randomUUID();
  const nowIso = new Date().toISOString();
  await env.DB.prepare(
    `INSERT INTO tasks (id, job_id, task_group, task_group_order, title, status, assigned_to, scheduled_date, notes, sort_order, is_punch_list, created_at)
     VALUES (?, ?, ?, ?, ?, 'pending', ?, ?, ?, ?, ?, ?)`,
  )
    .bind(
      id,
      jobId,
      taskGroup,
      groupOrder,
      title,
      str(body.assigned_to),
      str(body.scheduled_date),
      str(body.notes),
      sortOrder,
      body.is_punch_list ? 1 : 0,
      nowIso,
    )
    .run();

  await logAudit(env, user.email, "task_created", "job", jobId, { task_id: id, task_group: taskGroup, title });
  return json({ task: await loadTask(env, id) }, { status: 201 });
}

export async function handleTaskUpdate(request: Request, env: Env, taskId: string): Promise<Response> {
  const guarded = await guard(request, env, [...WRITE_ROLES]);
  if (guarded instanceof Response) return guarded;
  const { user } = guarded;

  const existing = await loadTask(env, taskId);
  if (!existing) return err(404, "not_found", "Task not found.");

  const body = await readJson(request);
  if (!body) return err(400, "bad_request", "Body must be JSON");

  const sets: string[] = [];
  const binds: unknown[] = [];
  const strFields = ["title", "task_group", "assigned_to", "scheduled_date", "notes"];
  for (const f of strFields) {
    if (f in body) {
      sets.push(`${f} = ?`);
      binds.push(str(body[f]));
    }
  }
  if ("sort_order" in body && Number.isFinite(Number(body.sort_order))) {
    sets.push("sort_order = ?");
    binds.push(Number(body.sort_order));
  }
  if ("is_punch_list" in body) {
    sets.push("is_punch_list = ?");
    binds.push(body.is_punch_list ? 1 : 0);
  }
  if ("status" in body) {
    const s = str(body.status);
    const valid = new Set(["pending", "in_progress", "complete", "skipped"]);
    if (!s || !valid.has(s)) return err(400, "bad_request", "Invalid task status.");
    sets.push("status = ?");
    binds.push(s);
    // Keep completion stamps consistent when status is set directly.
    if (s === "complete") {
      sets.push("completed_date = COALESCE(completed_date, ?)", "completed_by = COALESCE(completed_by, ?)");
      binds.push(new Date().toISOString(), user.email);
    } else {
      sets.push("completed_date = NULL", "completed_by = NULL");
    }
  }
  // If task_group changes to a brand-new group, give it the next group order.
  if ("task_group" in body) {
    const newGroup = str(body.task_group);
    if (newGroup) {
      const sib = await env.DB.prepare(
        "SELECT task_group_order FROM tasks WHERE job_id = ? AND task_group = ? AND id != ? LIMIT 1",
      )
        .bind(existing.job_id, newGroup, taskId)
        .first<{ task_group_order: number }>();
      let order = sib?.task_group_order;
      if (order == null) {
        const maxRow = await env.DB.prepare(
          "SELECT COALESCE(MAX(task_group_order), -1) AS m FROM tasks WHERE job_id = ?",
        )
          .bind(existing.job_id)
          .first<{ m: number }>();
        order = (maxRow?.m ?? -1) + 1;
      }
      sets.push("task_group_order = ?");
      binds.push(order);
    }
  }

  if (sets.length === 0) return err(400, "bad_request", "No updatable fields provided.");
  binds.push(taskId);
  await env.DB.prepare(`UPDATE tasks SET ${sets.join(", ")} WHERE id = ?`).bind(...binds).run();
  await logAudit(env, user.email, "task_updated", "job", existing.job_id, { task_id: taskId });

  return json({ task: await loadTask(env, taskId) });
}

export async function handleTaskComplete(request: Request, env: Env, taskId: string): Promise<Response> {
  const guarded = await guard(request, env, ["owner", "project_manager", "office_admin", "field_crew"]);
  if (guarded instanceof Response) return guarded;
  const { user } = guarded;

  const existing = await loadTask(env, taskId);
  if (!existing) return err(404, "not_found", "Task not found.");

  const nowIso = new Date().toISOString();
  await env.DB.prepare(
    "UPDATE tasks SET status = 'complete', completed_date = ?, completed_by = ? WHERE id = ?",
  )
    .bind(nowIso, user.email, taskId)
    .run();
  await logAudit(env, user.email, "task_completed", "job", existing.job_id, {
    task_id: taskId,
    task_group: existing.task_group,
  });

  return json({ task: await loadTask(env, taskId) });
}

async function loadTask(env: Env, taskId: string): Promise<ReturnType<typeof shapeTask> | null> {
  const r = await env.DB.prepare("SELECT * FROM tasks WHERE id = ?").bind(taskId).first<TaskRow>();
  return r ? shapeTask(r) : null;
}

async function nextSortOrder(env: Env, jobId: string, taskGroup: string): Promise<number> {
  const row = await env.DB.prepare(
    "SELECT COALESCE(MAX(sort_order), -1) AS m FROM tasks WHERE job_id = ? AND task_group = ?",
  )
    .bind(jobId, taskGroup)
    .first<{ m: number }>();
  return (row?.m ?? -1) + 1;
}

function round2(n: number): number {
  return Math.round((n + Number.EPSILON) * 100) / 100;
}

// ─── GET /api/jobs/map ────────────────────────────────────────────────────────

interface MapJobRow {
  id: string;
  job_number: number | null;
  title: string | null;
  status: string;
  property_address: string | null;
  property_city: string | null;
  property_state: string | null;
  property_zip: string | null;
  lat: number | null;
  lon: number | null;
  client_name: string | null;
}

interface MapPin {
  job_id: string;
  job_number: number | null;
  title: string | null;
  status: string;
  client_name: string | null;
  address: string;
  lat: number;
  lon: number;
}

// In-memory geocode cache keyed on normalized address string. No TTL — job
// addresses don't change, and this warms quickly since jobs are few.
const _geocodeCache = new Map<string, { lat: number; lon: number }>();

async function geocodeAddress(address: string): Promise<{ lat: number; lon: number } | null> {
  const key = address.toLowerCase().trim();
  const cached = _geocodeCache.get(key);
  if (cached) return cached;

  const url =
    `https://geocoding.geo.census.gov/geocoder/locations/onelineaddress` +
    `?address=${encodeURIComponent(address)}&benchmark=2020&format=json`;
  try {
    const res = await fetch(url);
    if (!res.ok) return null;
    const data = (await res.json()) as {
      result?: { addressMatches?: Array<{ coordinates?: { x: number; y: number } }> };
    };
    const coords = data?.result?.addressMatches?.[0]?.coordinates;
    if (!coords) return null;
    const result = { lat: coords.y, lon: coords.x };
    _geocodeCache.set(key, result);
    return result;
  } catch {
    return null;
  }
}

export async function handleJobMap(request: Request, env: Env): Promise<Response> {
  const guarded = await guard(request, env, ["owner", "project_manager", "office_admin"]);
  if (guarded instanceof Response) return guarded;

  const rows = (
    await env.DB.prepare(
      `SELECT j.id, j.job_number, j.title, j.status,
              j.property_address, j.property_city, j.property_state, j.property_zip,
              j.lat, j.lon,
              (c.first_name || ' ' || c.last_name) AS client_name
       FROM jobs j
       LEFT JOIN clients c ON c.id = j.client_id
       WHERE j.status NOT IN ('closed')
         AND (${NON_TEST_CLIENT})
       ORDER BY j.created_at DESC`,
    ).all<MapJobRow>()
  ).results ?? [];

  const pins: MapPin[] = [];
  const skipped: string[] = [];

  const needsGeocode: MapJobRow[] = [];

  for (const row of rows) {
    const addressLabel = [row.property_address, row.property_city, row.property_state]
      .filter(Boolean)
      .join(", ");

    if (row.lat != null && row.lon != null && Number.isFinite(row.lat) && Number.isFinite(row.lon)) {
      pins.push({
        job_id: row.id,
        job_number: row.job_number,
        title: row.title,
        status: row.status,
        client_name: row.client_name,
        address: addressLabel,
        lat: row.lat,
        lon: row.lon,
      });
      continue;
    }

    needsGeocode.push(row);
  }

  // Census geocode only for jobs without stored coordinates (batched).
  for (let i = 0; i < needsGeocode.length; i += 5) {
    const batch = needsGeocode.slice(i, i + 5);
    const results = await Promise.all(
      batch.map(async (row) => {
        const parts = [
          row.property_address,
          row.property_city,
          row.property_state ?? "AR",
          row.property_zip,
        ]
          .filter(Boolean)
          .join(", ");
        if (!parts) return { row, coords: null };
        const coords = await geocodeAddress(parts);
        return { row, coords };
      }),
    );
    for (const { row, coords } of results) {
      if (!coords) {
        skipped.push(row.id);
        continue;
      }
      const addressLabel = [row.property_address, row.property_city, row.property_state]
        .filter(Boolean)
        .join(", ");
      pins.push({
        job_id: row.id,
        job_number: row.job_number,
        title: row.title,
        status: row.status,
        client_name: row.client_name,
        address: addressLabel,
        lat: coords.lat,
        lon: coords.lon,
      });
    }
  }

  return json({ pins, skipped });
}

// ─── DELETE /api/jobs/:id ─────────────────────────────────────────────────────

export async function handleJobDelete(request: Request, env: Env, id: string): Promise<Response> {
  const guarded = await guard(request, env, [...WRITE_ROLES]);
  if (guarded instanceof Response) return guarded;
  const { user } = guarded;

  const job = await env.DB.prepare(
    `SELECT id, job_number, title, status, client_id, estimate_id
     FROM jobs WHERE id = ? AND ${nativeJobSourceWhere()}`,
  )
    .bind(id)
    .first<{
      id: string;
      job_number: number | null;
      title: string | null;
      status: string | null;
      client_id: string | null;
      estimate_id: string | null;
    }>();
  if (!job) return err(404, "not_found", "Job not found.");

  if (!job.status || !DELETABLE_JOB_STATUSES.has(job.status)) {
    return json(
      {
        error: "cannot_delete_active_job",
        message: "Only closed or cancelled jobs can be deleted.",
      },
      { status: 409 },
    );
  }

  const estimateId = job.estimate_id;
  await cascadeDeleteJob(env, id);
  await env.DB.prepare("DELETE FROM jobs WHERE id = ?").bind(id).run();

  if (estimateId) {
    await env.DB.prepare("UPDATE estimates SET status = 'archived' WHERE id = ?").bind(estimateId).run();
  }

  await logAudit(env, user.email, "job_deleted", "job", id, {
    job_number: job.job_number,
    title: job.title,
    status: job.status,
    client_id: job.client_id,
    estimate_id: estimateId,
  });

  return json({ ok: true, deleted: true, id });
}

// ────────────────────────────────────────────────────────────────────────────
// POST /api/jobs/quick — create a job directly (no estimate required).
//
// Narrow exception to the "jobs only via quote-to-job" rule, for
// hourly/simple-service client relationships where no estimate, scope, or
// signature applies. Lands on "in_progress" with Fixed Price billing by
// default — Financial tab is immediately ready for a manual invoice.
// ────────────────────────────────────────────────────────────────────────────

function strQ(body: Record<string, unknown>, key: string): string | null {
  const v = body[key];
  return typeof v === "string" && v.trim() ? v.trim() : null;
}

export async function handleJobQuickCreate(
  request: Request,
  env: Env,
): Promise<Response> {
  const guarded = await guard(request, env, ["owner", "project_manager", "office_admin"]);
  if (guarded instanceof Response) return guarded;
  const { user } = guarded;

  let body: Record<string, unknown>;
  try {
    body = (await request.json()) as Record<string, unknown>;
  } catch {
    return err(400, "bad_request", "Body must be JSON");
  }

  const clientId = strQ(body, "client_id");
  if (!clientId) return err(400, "bad_request", "client_id is required");

  const client = await env.DB.prepare(
    "SELECT id, first_name, last_name, name FROM clients WHERE id = ?",
  )
    .bind(clientId)
    .first<{ id: string; first_name: string | null; last_name: string | null; name: string | null }>();
  if (!client) return err(404, "not_found", "Client not found");

  const billingModel = strQ(body, "billing_model") ?? "fixed_price";
  const portalType = billingModel === "cost_plus" ? "cost_plus" : "standard";
  const clientLabel =
    [client.first_name, client.last_name].filter(Boolean).join(" ").trim() ||
    client.name ||
    "Client";
  const title = strQ(body, "title") ?? `Quick Job — ${clientLabel}`;
  const jobType = strQ(body, "job_type") ?? "Hourly / Simple Service";
  const propertyAddress = strQ(body, "property_address");
  const propertyCity = strQ(body, "property_city");
  const propertyState = strQ(body, "property_state");
  const propertyZip = strQ(body, "property_zip");

  const jobId = crypto.randomUUID();
  const portalToken = crypto.randomUUID().replace(/-/g, "");
  const now = new Date().toISOString();

  await env.DB.prepare(
    `INSERT INTO jobs (
       id, job_number, title, status, client_id, source, total,
       created_at, synced_at, updated_at,
       billing_model, property_address, property_city, property_state, property_zip,
       job_type, estimate_id, portal_token, portal_type, conversion_complete
     )
     SELECT
       ?, COALESCE((SELECT MAX(job_number) FROM jobs), 0) + 1,
       ?, 'in_progress', ?, 'quick_job', 0,
       ?, ?, ?,
       ?, ?, ?, ?, ?,
       ?, NULL, ?, ?, 1`,
  )
    .bind(
      jobId,
      title,
      clientId,
      now,
      now, // synced_at NOT NULL (legacy Jobber-sync column; set to creation time for native rows)
      now,
      billingModel,
      propertyAddress,
      propertyCity,
      propertyState,
      propertyZip,
      jobType,
      portalToken,
      portalType,
    )
    .run();

  const jobRow = await env.DB.prepare("SELECT id, job_number FROM jobs WHERE id = ?")
    .bind(jobId)
    .first<{ id: string; job_number: number }>();

  await logAudit(env, user.email, "quick_job_created", "job", jobId, {
    job_number: jobRow?.job_number,
    client_id: clientId,
    billing_model: billingModel,
    title,
  });

  return json({ job: { id: jobId, job_number: jobRow?.job_number ?? null } }, { status: 201 });
}

// ── POST /api/jobs/:id/test-weekly-recap (owner-only, test trigger) ───────────
/**
 * Manually fires the weekly recap generation + real email send for a single job.
 * Owner-only. Does NOT affect the real Sunday cron schedule.
 * Exists as a permanent spot-check capability — see CHS-Bundle-WeeklyRecapTrigger task.
 */
export async function handleTestWeeklyRecap(
  request: Request,
  env: Env,
  jobId: string,
): Promise<Response> {
  const authed = await guard(request, env, ["owner"]);
  if (authed instanceof Response) return authed;

  const job = await env.DB.prepare(
    `SELECT id, title, client_id, portal_token, billing_model, portal_type FROM jobs WHERE id = ?`,
  )
    .bind(jobId)
    .first<{
      id: string;
      title: string | null;
      client_id: string | null;
      portal_token: string | null;
      billing_model: string | null;
      portal_type: string | null;
    }>();
  if (!job) return err(404, "job_not_found");

  const client = job.client_id
    ? await env.DB.prepare(
        `SELECT email, first_name, last_name FROM clients WHERE id = ?`,
      )
        .bind(job.client_id)
        .first<{ email: string | null; first_name: string | null; last_name: string | null }>()
    : null;

  if (!client?.email) return err(400, "client_has_no_email");

  // Photo count for the last 7 days (mirrors runWeeklyPhotoSummary's query window)
  const photoRow = await env.DB.prepare(
    `SELECT COUNT(*) AS cnt FROM photos WHERE job_id = ? AND is_active = 1 AND created_at >= datetime('now', '-7 days')`,
  )
    .bind(jobId)
    .first<{ cnt: number }>();
  const photoCount = photoRow?.cnt ?? 0;

  const today = new Date().toISOString().slice(0, 10);
  const weekStart = new Date(Date.now() - 7 * 86_400_000).toISOString().slice(0, 10);

  const isCostPlus =
    (job.billing_model ?? "").toLowerCase() === "cost_plus" ||
    (job.portal_type ?? "").toLowerCase() === "cost_plus";

  const recap = await generateWeeklyRecap(env, {
    jobId,
    jobTitle: job.title ?? "your project",
    weekStart,
    weekEnd: today,
    photoCount,
    isCostPlus,
  });

  const origin = (env.APP_PUBLIC_ORIGIN ?? "https://client.homesolutionsar.com").replace(/\/$/, "");
  const portalLink = job.portal_token ? `${origin}/portal/${job.portal_token}` : origin;
  const clientName =
    [client.first_name, client.last_name].filter(Boolean).join(" ") || "there";

  const emailBody =
    `Hi ${clientName},\n\nHere's your weekly project update for "${job.title ?? "your project"}":\n\n` +
    `${recap}\n\n` +
    `View your project portal: ${portalLink}\n\n` +
    `— Columbus Home Solutions`;

  await sendSubEmail(
    env,
    client.email,
    `Weekly Update: ${job.title ?? "Your Project"}`,
    emailBody,
  );

  await logAudit(env, authed.user.email, "test_weekly_recap_sent", "job", jobId, {
    sent_to: client.email,
    week_start: weekStart,
    week_end: today,
    photo_count: photoCount,
  });

  return json({
    ok: true,
    recap,
    sent_to: client.email,
    photo_count: photoCount,
    week_start: weekStart,
    week_end: today,
  });
}
