/**
 * Manual trigger + introspection routes for the reliability subsystem.
 *
 * All write/trigger endpoints require ?secret=<SYNC_TRIGGER_SECRET> or the
 * x-sync-token header. Read endpoints (DLQ summary, heartbeat status) are
 * gated the same way to keep the workers.dev URL safe — the dashboard
 * itself is behind Cloudflare Access so we don't need to worry about that.
 */

import type { Env } from "../env.js";
import { runBackup, getLatestBackup } from "../lib/ops/backup.js";
import { sendDailySummary } from "../lib/ops/daily-summary.js";
import { getDlqSummary, replayDeadLetters } from "../lib/ops/dlq.js";
import { checkHeartbeat } from "../lib/ops/heartbeat.js";
import { notify } from "../lib/ops/notify.js";
import { getDriveMirrorStatus, runDriveMirror } from "../lib/ops/drive-mirror.js";
import { maybeAutoGenerateDocument } from "../lib/document-autotrigger.js";
import type { TemplateType } from "./job-documents.js";
import {
  downloadSignedDocument,
  getBoldSignConfig,
  getDocumentProperties,
  revokeDocument,
  sendDocumentForSignature,
} from "../lib/boldsign.js";

function requireSecret(request: Request, env: Env): Response | null {
  const url = new URL(request.url);
  const secret =
    url.searchParams.get("secret") ?? request.headers.get("x-sync-token") ?? "";
  if (secret !== env.SYNC_TRIGGER_SECRET) {
    return new Response("Forbidden", { status: 403 });
  }
  return null;
}

function jsonOk(payload: unknown, status = 200): Response {
  return new Response(JSON.stringify(payload, null, 2), {
    status,
    headers: { "content-type": "application/json", "cache-control": "no-store" },
  });
}

export async function handleHeartbeatCheck(
  request: Request,
  env: Env,
): Promise<Response> {
  const guard = requireSecret(request, env);
  if (guard) return guard;
  const status = await checkHeartbeat(env);
  return jsonOk(status);
}

export async function handleDlqSummary(
  request: Request,
  env: Env,
): Promise<Response> {
  const guard = requireSecret(request, env);
  if (guard) return guard;
  const summary = await getDlqSummary(env);
  return jsonOk(summary);
}

export async function handleDlqReplay(
  request: Request,
  env: Env,
): Promise<Response> {
  const guard = requireSecret(request, env);
  if (guard) return guard;
  const result = await replayDeadLetters(env);
  return jsonOk(result);
}

export async function handleBackupRun(
  request: Request,
  env: Env,
): Promise<Response> {
  const guard = requireSecret(request, env);
  if (guard) return guard;
  const result = await runBackup(env);
  return jsonOk(result, result.ok ? 200 : 500);
}

export async function handleBackupLatest(
  request: Request,
  env: Env,
): Promise<Response> {
  const guard = requireSecret(request, env);
  if (guard) return guard;
  const latest = await getLatestBackup(env);
  return jsonOk(latest ?? { latest: null });
}

export async function handleSummarySend(
  request: Request,
  env: Env,
): Promise<Response> {
  const guard = requireSecret(request, env);
  if (guard) return guard;
  const result = await sendDailySummary(env);
  return jsonOk(result);
}

export async function handleAlertTest(
  request: Request,
  env: Env,
): Promise<Response> {
  const guard = requireSecret(request, env);
  if (guard) return guard;
  const result = await notify(env, {
    severity: "info",
    subject: "Test notification",
    text: `Hello from chs-hub at ${new Date().toISOString()}.\n\nIf you're reading this, the notify pipeline is working.`,
  });
  return jsonOk(result);
}

export async function handleDriveMirrorStatus(
  request: Request,
  env: Env,
): Promise<Response> {
  const guard = requireSecret(request, env);
  if (guard) return guard;
  const status = await getDriveMirrorStatus(env);
  return jsonOk(status);
}

export async function handleDriveMirrorRun(
  request: Request,
  env: Env,
): Promise<Response> {
  const guard = requireSecret(request, env);
  if (guard) return guard;
  const result = await runDriveMirror(env);
  return jsonOk(result);
}

/**
 * POST /api/ops/autogen-document?job_id=&template_type=warranty_certificate
 * Optional: related_record_id (e.g. change_order id), force=1 to discard an existing
 * pending_review/approved row for the same (job, type, related) before regenerating.
 */
export async function handleOpsAutogenDocument(
  request: Request,
  env: Env,
): Promise<Response> {
  const guard = requireSecret(request, env);
  if (guard) return guard;
  const url = new URL(request.url);
  const jobId = url.searchParams.get("job_id")?.trim();
  const templateType = (url.searchParams.get("template_type")?.trim() ||
    "warranty_certificate") as TemplateType;
  const relatedRecordId = url.searchParams.get("related_record_id")?.trim() || null;
  const force = url.searchParams.get("force") === "1";
  if (!jobId) return jsonOk({ error: "job_id required" }, 400);

  if (force) {
    await env.DB.prepare(
      `UPDATE job_documents
          SET review_status = 'discarded'
        WHERE job_id = ?
          AND template_type = ?
          AND review_status IN ('pending_review', 'approved')
          AND (
            (? IS NULL AND related_record_id IS NULL)
            OR related_record_id = ?
          )`,
    )
      .bind(jobId, templateType, relatedRecordId, relatedRecordId)
      .run();
  }

  const triggerEvent =
    templateType === "change_order"
      ? "change_order_approved"
      : templateType === "warranty_certificate"
        ? "job_complete"
        : "client_payment";

  const result = await maybeAutoGenerateDocument(env, {
    jobId,
    templateType,
    triggerEvent,
    relatedRecordId,
  });
  return jsonOk(result);
}

type GhostProofPathResult = {
  path: string;
  ok: boolean;
  documentId?: string;
  boldSignStatus?: string | null;
  hasSignTag: boolean;
  hasDateTag: boolean;
  hasDocumentIdFooter: boolean;
  pdfBytes?: number;
  error?: string;
};

function scanPdfGhosts(pdf: ArrayBuffer): {
  hasSignTag: boolean;
  hasDateTag: boolean;
  hasDocumentIdFooter: boolean;
} {
  // BoldSign PDFs usually keep tag / Document ID strings as literal content.
  const text = new TextDecoder("latin1").decode(new Uint8Array(pdf));
  return {
    hasSignTag: text.includes("{{sign|"),
    hasDateTag: text.includes("{{date|"),
    hasDocumentIdFooter: /Document\s*ID\s*:/i.test(text),
  };
}

async function sleep(ms: number): Promise<void> {
  await new Promise((r) => setTimeout(r, ms));
}

/**
 * POST /api/ops/boldsign-ghost-proof
 *
 * Temporary proof harness for the Round-4 ghosted-tag fix. Sends real BoldSign
 * docs through each distinct send mode, downloads the PDF, and scans the bytes
 * for leftover {{sign|/{{date| tags and the Document ID footer. Revokes after.
 */
export async function handleOpsBoldsignGhostProof(
  request: Request,
  env: Env,
): Promise<Response> {
  const guard = requireSecret(request, env);
  if (guard) return guard;

  const config = await getBoldSignConfig(env);
  if (!config) {
    return jsonOk({ error: "BOLDSIGN_API_KEY not configured" }, 503);
  }

  const url = new URL(request.url);
  const signerEmail =
    url.searchParams.get("signer_email")?.trim() || "tony@homesolutionsar.com";
  const signerName = "Ghost Proof Test";
  const onlyPath = url.searchParams.get("path")?.trim() || "";
  const existingId = url.searchParams.get("document_id")?.trim() || "";

  // Re-scan an already-sent BoldSign doc (avoids another send + wait).
  if (existingId) {
    try {
      const props = await getDocumentProperties(config, existingId);
      const pdf = await downloadSignedDocument(config, existingId);
      const scan = scanPdfGhosts(pdf);
      return jsonOk({
        generated_at: new Date().toISOString(),
        path: "existing_document",
        documentId: existingId,
        boldSignStatus: props?.status ?? null,
        pdfBytes: pdf.byteLength,
        ...scan,
        ok: !scan.hasSignTag && !scan.hasDateTag && !scan.hasDocumentIdFooter,
      });
    } catch (e) {
      return jsonOk({ error: (e as Error).message, documentId: existingId }, 502);
    }
  }

  const r2Keys: Array<{ path: string; key: string; mode: "text_tags" | "template" }> = [
    {
      path: "estimate_sa_text_tags",
      key: "documents/templates/service-agreement.docx",
      mode: "text_tags",
    },
    {
      path: "estimate_selection_combined_text_tags",
      key: "documents/templates/selection-combined-approval.docx",
      mode: "text_tags",
    },
    {
      path: "job_lien_waiver_template_id",
      key: "documents/templates/lien-waiver-conditional.docx",
      mode: "template",
    },
    {
      path: "sub_agreement_text_tags",
      key: "documents/templates/subcontractor-agreement.docx",
      mode: "text_tags",
    },
  ];

  const selected = onlyPath
    ? r2Keys.filter((r) => r.path === onlyPath)
    : r2Keys.slice(0, 1); // default: one path to stay under subrequest limits
  if (onlyPath && selected.length === 0) {
    return jsonOk(
      { error: "unknown path", known: r2Keys.map((r) => r.path) },
      400,
    );
  }

  const results: GhostProofPathResult[] = [];

  for (const item of selected) {
    const row: GhostProofPathResult = {
      path: item.path,
      ok: false,
      hasSignTag: true,
      hasDateTag: true,
      hasDocumentIdFooter: true,
    };
    try {
      const obj = await env.FILES.get(item.key);
      if (!obj && item.mode === "text_tags") {
        row.error = `R2 missing ${item.key}`;
        results.push(row);
        continue;
      }

      let documentId: string;
      if (item.mode === "text_tags") {
        const bytes = await obj!.arrayBuffer();
        const send = await sendDocumentForSignature(config, {
          fileBlob: new Blob([bytes], {
            type: "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
          }),
          filename: `${item.path}.docx`,
          title: `[GHOST-PROOF] ${item.path}`,
          message: "Automated ghost-tag proof — revoke after scan.",
          signerEmail,
          signerName,
          useTextTags: true,
        });
        documentId = send.documentId;
      } else {
        const send = await sendDocumentForSignature(config, {
          fileBlob: new Blob(["unused"], { type: "application/octet-stream" }),
          filename: "unused.docx",
          title: `[GHOST-PROOF] ${item.path}`,
          message: "Automated ghost-tag proof — revoke after scan.",
          signerEmail,
          signerName,
          templateId: "7d6692c2-21e9-4ae9-ba2a-7f45c1f33eba",
          signerRole: "Client",
          roleIndex: 2,
        });
        documentId = send.documentId;
      }

      row.documentId = documentId;

      // BoldSign conversion is async — poll download only (few subrequests).
      let pdf: ArrayBuffer | null = null;
      let status: string | null | undefined = null;
      for (let attempt = 0; attempt < 10; attempt++) {
        await sleep(4000);
        try {
          pdf = await downloadSignedDocument(config, documentId);
          const props = await getDocumentProperties(config, documentId);
          status = props?.status ?? null;
          break;
        } catch {
          // still processing
        }
      }
      row.boldSignStatus = status;

      if (!pdf) {
        row.error = "download timed out";
        results.push(row);
        try {
          await revokeDocument(config, documentId, "ghost-proof cleanup");
        } catch {
          /* ignore */
        }
        continue;
      }

      const scan = scanPdfGhosts(pdf);
      row.hasSignTag = scan.hasSignTag;
      row.hasDateTag = scan.hasDateTag;
      row.hasDocumentIdFooter = scan.hasDocumentIdFooter;
      row.pdfBytes = pdf.byteLength;

      // Surface signature/date field bounds so we can catch 1pt-shrink regressions.
      const propsRes = await fetch(
        `https://api.boldsign.com/v1/document/properties?documentId=${encodeURIComponent(documentId)}`,
        { headers: { "X-API-KEY": config.apiKey } },
      );
      if (propsRes.ok) {
        const props = (await propsRes.json()) as {
          status?: string;
          signerDetails?: Array<{
            formFields?: Array<{
              type?: string;
              fieldType?: string;
              name?: string;
              bounds?: { x?: number; y?: number; width?: number; height?: number };
              Bounds?: { X?: number; Y?: number; Width?: number; Height?: number };
            }>;
          }>;
        };
        row.boldSignStatus = props.status ?? row.boldSignStatus;
        const fields = (props.signerDetails ?? []).flatMap((s) => s.formFields ?? []);
        (row as GhostProofPathResult & { formFields?: unknown }).formFields = fields.map((f) => {
          const b = f.bounds ?? f.Bounds ?? {};
          return {
            type: f.type ?? f.fieldType ?? f.name,
            width: (b as { width?: number; Width?: number }).width ?? (b as { Width?: number }).Width,
            height: (b as { height?: number; Height?: number }).height ?? (b as { Height?: number }).Height,
            x: (b as { x?: number; X?: number }).x ?? (b as { X?: number }).X,
            y: (b as { y?: number; Y?: number }).y ?? (b as { Y?: number }).Y,
          };
        });
        const sig = (row as { formFields?: Array<{ type?: string; width?: number; height?: number }> })
          .formFields?.find((f) =>
            String(f.type ?? "").toLowerCase().includes("sign"),
          );
        // Tiny signature boxes (height/width under ~20) indicate the 1pt shrink bug.
        if (sig && ((sig.width ?? 0) < 40 || (sig.height ?? 0) < 15)) {
          row.ok = false;
          row.error = `signature field too small: ${JSON.stringify(sig)}`;
        }
      }

      // Template-id path has no text tags in our upload; only Document ID matters.
      if (!row.error) {
        row.ok =
          item.mode === "template"
            ? !scan.hasDocumentIdFooter
            : !scan.hasSignTag && !scan.hasDateTag && !scan.hasDocumentIdFooter;
      }

      try {
        await revokeDocument(config, documentId, "ghost-proof cleanup");
      } catch (e) {
        row.error = `revoke: ${(e as Error).message}`;
      }
    } catch (e) {
      row.error = (e as Error).message;
    }
    results.push(row);
  }

  return jsonOk({
    generated_at: new Date().toISOString(),
    all_ok: results.every((r) => r.ok),
    results,
    note:
      "Scans raw PDF bytes for {{sign|, {{date|, and Document ID:. " +
      "Unsigned downloads are valid for ghost detection.",
  });
}
