/**
 * Manual trigger + introspection routes for the reliability subsystem.
 *
 * All write/trigger endpoints require ?secret=<SYNC_TRIGGER_SECRET> or the
 * x-sync-token header. Read endpoints (DLQ summary, heartbeat status) are
 * gated the same way to keep the workers.dev URL safe — the dashboard
 * itself is behind Cloudflare Access so we don't need to worry about that.
 */

import type { Env } from "../env.js";
import { runBackup, getLatestBackup } from "../lib/ops/backup.js";
import { sendDailySummary } from "../lib/ops/daily-summary.js";
import { getDlqSummary, replayDeadLetters } from "../lib/ops/dlq.js";
import { checkHeartbeat } from "../lib/ops/heartbeat.js";
import { notify } from "../lib/ops/notify.js";
import { getDriveMirrorStatus, runDriveMirror } from "../lib/ops/drive-mirror.js";
import { maybeAutoGenerateDocument } from "../lib/document-autotrigger.js";
import type { TemplateType } from "./job-documents.js";
import {
  downloadSignedDocument,
  getBoldSignConfig,
  getDocumentProperties,
  getEmbeddedSignLink,
  revokeDocument,
  sendDocumentForSignature,
} from "../lib/boldsign.js";
import {
  resendCombinedSelectionApprovalForEstimate,
  sendCombinedSelectionApprovalForEstimate,
} from "./selections.js";
import {
  generateAndSendEstimateContract,
  parseSignatureMeta,
} from "../lib/estimate-contract-document.js";
function requireSecret(request: Request, env: Env): Response | null {
  const url = new URL(request.url);
  const secret =
    url.searchParams.get("secret") ?? request.headers.get("x-sync-token") ?? "";
  if (secret !== env.SYNC_TRIGGER_SECRET) {
    return new Response("Forbidden", { status: 403 });
  }
  return null;
}

function jsonOk(payload: unknown, status = 200): Response {
  return new Response(JSON.stringify(payload, null, 2), {
    status,
    headers: { "content-type": "application/json", "cache-control": "no-store" },
  });
}

export async function handleHeartbeatCheck(
  request: Request,
  env: Env,
): Promise<Response> {
  const guard = requireSecret(request, env);
  if (guard) return guard;
  const status = await checkHeartbeat(env);
  return jsonOk(status);
}

export async function handleDlqSummary(
  request: Request,
  env: Env,
): Promise<Response> {
  const guard = requireSecret(request, env);
  if (guard) return guard;
  const summary = await getDlqSummary(env);
  return jsonOk(summary);
}

export async function handleDlqReplay(
  request: Request,
  env: Env,
): Promise<Response> {
  const guard = requireSecret(request, env);
  if (guard) return guard;
  const result = await replayDeadLetters(env);
  return jsonOk(result);
}

export async function handleBackupRun(
  request: Request,
  env: Env,
): Promise<Response> {
  const guard = requireSecret(request, env);
  if (guard) return guard;
  const result = await runBackup(env);
  return jsonOk(result, result.ok ? 200 : 500);
}

export async function handleBackupLatest(
  request: Request,
  env: Env,
): Promise<Response> {
  const guard = requireSecret(request, env);
  if (guard) return guard;
  const latest = await getLatestBackup(env);
  return jsonOk(latest ?? { latest: null });
}

export async function handleSummarySend(
  request: Request,
  env: Env,
): Promise<Response> {
  const guard = requireSecret(request, env);
  if (guard) return guard;
  const result = await sendDailySummary(env);
  return jsonOk(result);
}

export async function handleAlertTest(
  request: Request,
  env: Env,
): Promise<Response> {
  const guard = requireSecret(request, env);
  if (guard) return guard;
  const result = await notify(env, {
    severity: "info",
    subject: "Test notification",
    text: `Hello from chs-hub at ${new Date().toISOString()}.\n\nIf you're reading this, the notify pipeline is working.`,
  });
  return jsonOk(result);
}

export async function handleDriveMirrorStatus(
  request: Request,
  env: Env,
): Promise<Response> {
  const guard = requireSecret(request, env);
  if (guard) return guard;
  const status = await getDriveMirrorStatus(env);
  return jsonOk(status);
}

export async function handleDriveMirrorRun(
  request: Request,
  env: Env,
): Promise<Response> {
  const guard = requireSecret(request, env);
  if (guard) return guard;
  const result = await runDriveMirror(env);
  return jsonOk(result);
}

/**
 * POST /api/ops/autogen-document?job_id=&template_type=warranty_certificate
 * Optional: related_record_id (e.g. change_order id), force=1 to discard an existing
 * pending_review/approved row for the same (job, type, related) before regenerating.
 */
export async function handleOpsAutogenDocument(
  request: Request,
  env: Env,
): Promise<Response> {
  const guard = requireSecret(request, env);
  if (guard) return guard;
  const url = new URL(request.url);
  const jobId = url.searchParams.get("job_id")?.trim();
  const templateType = (url.searchParams.get("template_type")?.trim() ||
    "warranty_certificate") as TemplateType;
  const relatedRecordId = url.searchParams.get("related_record_id")?.trim() || null;
  const force = url.searchParams.get("force") === "1";
  if (!jobId) return jsonOk({ error: "job_id required" }, 400);

  if (force) {
    await env.DB.prepare(
      `UPDATE job_documents
          SET review_status = 'discarded'
        WHERE job_id = ?
          AND template_type = ?
          AND review_status IN ('pending_review', 'approved')
          AND (
            (? IS NULL AND related_record_id IS NULL)
            OR related_record_id = ?
          )`,
    )
      .bind(jobId, templateType, relatedRecordId, relatedRecordId)
      .run();
  }

  const triggerEvent =
    templateType === "change_order"
      ? "change_order_approved"
      : templateType === "warranty_certificate"
        ? "job_complete"
        : "client_payment";

  const result = await maybeAutoGenerateDocument(env, {
    jobId,
    templateType,
    triggerEvent,
    relatedRecordId,
  });
  return jsonOk(result);
}

type GhostProofPathResult = {
  path: string;
  ok: boolean;
  documentId?: string;
  boldSignStatus?: string | null;
  hasSignTag: boolean;
  hasDateTag: boolean;
  hasDocumentIdFooter: boolean;
  pdfBytes?: number;
  error?: string;
};

function scanPdfGhosts(pdf: ArrayBuffer): {
  hasSignTag: boolean;
  hasDateTag: boolean;
  hasDocumentIdFooter: boolean;
} {
  // BoldSign PDFs usually keep tag / Document ID strings as literal content.
  const text = new TextDecoder("latin1").decode(new Uint8Array(pdf));
  return {
    hasSignTag: text.includes("{{sign|"),
    hasDateTag: text.includes("{{date|"),
    hasDocumentIdFooter: /Document\s*ID\s*:/i.test(text),
  };
}

async function sleep(ms: number): Promise<void> {
  await new Promise((r) => setTimeout(r, ms));
}

/**
 * POST /api/ops/boldsign-ghost-proof
 *
 * Temporary proof harness for the Round-4 ghosted-tag fix. Sends real BoldSign
 * docs through each distinct send mode, downloads the PDF, and scans the bytes
 * for leftover {{sign|/{{date| tags and the Document ID footer. Revokes after.
 */
/**
 * POST /api/ops/resend-selection-approval?estimate_id=
 * Force-resends combined selection BoldSign (revokes collapsed 1pt-field docs).
 */
export async function handleOpsResendSelectionApproval(
  request: Request,
  env: Env,
): Promise<Response> {
  const guard = requireSecret(request, env);
  if (guard) return guard;
  const estimateId = new URL(request.url).searchParams.get("estimate_id")?.trim();
  if (!estimateId) return jsonOk({ error: "estimate_id required" }, 400);
  const origin = new URL(request.url).origin;
  return resendCombinedSelectionApprovalForEstimate(env, estimateId, origin);
}

const E2E_CLIENT_ID = "7c4a1f2e-8b3d-4e91-a5c6-2d8f9e1a3b4c"; // ZZTEST-PRELAUNCH

/**
 * POST /api/ops/e2e-fresh-estimate-setup
 * Creates a brand-new estimate + SA BoldSign send + selection BoldSign send.
 * Returns document IDs, field bounds, and embed sign links — no Access cookie needed.
 */
export async function handleOpsE2eFreshEstimateSetup(
  request: Request,
  env: Env,
): Promise<Response> {
  const guard = requireSecret(request, env);
  if (guard) return guard;

  try {
  const origin = "https://dashboard.homesolutionsar.com";
  const now = new Date().toISOString();
  const maxNum = await env.DB.prepare(
    "SELECT COALESCE(MAX(estimate_number), 0) AS n FROM estimates",
  ).first<{ n: number }>();
  const estimateNumber = (maxNum?.n ?? 0) + 1;
  const estimateId = crypto.randomUUID();
  const portalToken = crypto.randomUUID().replace(/-/g, "");
  const title = `E2E BoldSign Fresh EST-${estimateNumber} — ${now.slice(0, 16)}`;

  const client = await env.DB.prepare(
    "SELECT id, first_name, last_name, email FROM clients WHERE id = ?",
  )
    .bind(E2E_CLIENT_ID)
    .first<{ id: string; first_name: string | null; last_name: string | null; email: string | null }>();
  if (!client) return jsonOk({ error: "E2E test client missing" }, 500);

  await env.DB.prepare(
    `INSERT INTO estimates (
      id, estimate_number, request_id, client_id, title, estimate_mode, billing_model,
      status, subtotal, tax_amount, total, margin_percent,
      deposit_amount, deposit_type, deposit_percentage, valid_days,
      include_reviews, include_contract, version, portal_token,
      sent_at, expiration_date, created_at, updated_at, created_by
    ) VALUES (?, ?, NULL, ?, ?, 'trade_by_trade', 'fixed_price',
      'sent', 2500, 0, 2500, 0,
      750, 'percentage', 30, 7,
      1, 1, 1, ?,
      ?, date('now', '+7 days'), ?, ?, ?)`,
  )
    .bind(
      estimateId,
      estimateNumber,
      E2E_CLIENT_ID,
      title,
      portalToken,
      now,
      now,
      now,
      "00000000-0000-0000-0000-000000000001",
    )
    .run();

  const lineId = crypto.randomUUID();
  await env.DB.prepare(
    `INSERT INTO estimate_line_items
      (id, estimate_id, sort_order, product_service, description, quantity, unit, unit_price, total, created_at)
     VALUES (?, ?, 0, 'E2E Demo Line', 'Automated E2E — DELETE-ME', 1, 'ea', 2500, 2500, datetime('now'))`,
  )
    .bind(lineId, estimateId)
    .run();

  await env.DB.prepare(
    `INSERT INTO payment_schedules
      (id, estimate_id, sort_order, description, percentage, fixed_amount, amount, is_deposit, created_at)
     VALUES (?, ?, 0, 'Deposit', 30, NULL, NULL, 1, datetime('now'))`,
  )
    .bind(crypto.randomUUID(), estimateId)
    .run();
  await env.DB.prepare(
    `INSERT INTO payment_schedules
      (id, estimate_id, sort_order, description, percentage, fixed_amount, amount, is_deposit, created_at)
     VALUES (?, ?, 1, 'Final', 70, NULL, NULL, 0, datetime('now'))`,
  )
    .bind(crypto.randomUUID(), estimateId)
    .run();

  const selectionId = crypto.randomUUID();
  const choiceId = crypto.randomUUID();
  await env.DB.prepare(
    `INSERT INTO selections
      (id, estimate_id, job_id, title, category, allowance_amount, required, status,
       chosen_choice_id, created_at)
     VALUES (?, ?, NULL, 'Flooring Allowance', 'flooring', 1000, 1, 'pending', NULL, datetime('now'))`,
  )
    .bind(selectionId, estimateId)
    .run();
  await env.DB.prepare(
    `INSERT INTO selection_choices
      (id, selection_id, title, description, price, is_client_added, approved, created_at)
     VALUES (?, ?, 'LVP Standard', 'E2E choice', 900, 0, 0, datetime('now'))`,
  )
    .bind(choiceId, selectionId)
    .run();
  await env.DB.prepare(
    `UPDATE selections SET chosen_choice_id = ? WHERE id = ?`,
  )
    .bind(choiceId, selectionId)
    .run();

  const contractResult = await generateAndSendEstimateContract(
    env,
    estimateId,
    client.email ?? "tony@homesolutionsar.com",
  );
  if (!contractResult.boldsign_sent || !contractResult.docId) {
    return jsonOk(
      {
        error: "contract_send_failed",
        contractResult,
        estimateId,
        estimateNumber,
      },
      502,
    );
  }

  const selRes = await sendCombinedSelectionApprovalForEstimate(env, estimateId, origin);
  const selBody = (await selRes.json()) as {
    ok?: boolean;
    boldsign_document_id?: string;
    sign_link?: string | null;
    error?: string;
    details?: string;
  };
  if (!selRes.ok || !selBody.boldsign_document_id) {
    return jsonOk(
      {
        error: "selection_send_failed",
        selBody,
        estimateId,
        estimateNumber,
        contractDocId: contractResult.docId,
      },
      502,
    );
  }

  // Load contract boldsign id
  const contractDoc = await env.DB.prepare(
    "SELECT id, signature_data FROM documents WHERE id = ?",
  )
    .bind(contractResult.docId)
    .first<{ id: string; signature_data: string | null }>();
  const contractMeta = parseSignatureMeta(contractDoc?.signature_data);
  const contractBoldId = contractMeta.boldsign_document_id;
  if (!contractBoldId) {
    return jsonOk({ error: "contract_missing_boldsign_id", estimateId }, 502);
  }

  const config = await getBoldSignConfig(env);
  if (!config) return jsonOk({ error: "boldsign_unconfigured" }, 503);

  // Wait briefly for BoldSign async processing, then probe fields + embed links
  const sleep = (ms: number) => new Promise((r) => setTimeout(r, ms));
  await sleep(6000);

  async function fieldProbe(documentId: string) {
    const propsRes = await fetch(
      `https://api.boldsign.com/v1/document/properties?documentId=${encodeURIComponent(documentId)}`,
      { headers: { "X-API-KEY": config!.apiKey } },
    );
    if (!propsRes.ok) {
      return { error: await propsRes.text(), formFields: [] as Array<Record<string, unknown>> };
    }
    const full = (await propsRes.json()) as {
      status?: string;
      signerDetails?: Array<{
        formFields?: Array<{
          type?: string;
          fieldType?: string;
          bounds?: { width?: number; height?: number; x?: number; y?: number };
          Bounds?: { Width?: number; Height?: number; X?: number; Y?: number };
        }>;
      }>;
    };
    const formFields = (full.signerDetails ?? []).flatMap((s) => s.formFields ?? []).map((f) => {
      const b = f.bounds ?? f.Bounds ?? {};
      return {
        type: f.type ?? f.fieldType,
        width: (b as { width?: number; Width?: number }).width ?? (b as { Width?: number }).Width,
        height:
          (b as { height?: number; Height?: number }).height ?? (b as { Height?: number }).Height,
        x: (b as { x?: number; X?: number }).x ?? (b as { X?: number }).X,
        y: (b as { y?: number; Y?: number }).y ?? (b as { Y?: number }).Y,
      };
    });
    const sig = formFields.find((f) => String(f.type ?? "").toLowerCase().includes("sign"));
    return {
      status: full.status,
      formFields,
      signatureFieldOk: !!sig && (sig.width ?? 0) >= 40 && (sig.height ?? 0) >= 10,
    };
  }

  let contractProbe = await fieldProbe(contractBoldId);
  let selectionProbe = await fieldProbe(selBody.boldsign_document_id);
  for (let i = 0; i < 8; i++) {
    if (contractProbe.formFields?.length && selectionProbe.formFields?.length) break;
    await sleep(2500);
    if (!contractProbe.formFields?.length) contractProbe = await fieldProbe(contractBoldId);
    if (!selectionProbe.formFields?.length) {
      selectionProbe = await fieldProbe(selBody.boldsign_document_id);
    }
  }

  const signerEmail = client.email ?? "tony@homesolutionsar.com";
  let contractSignLink: string | null = null;
  let selectionSignLink: string | null = selBody.sign_link ?? null;
  try {
    contractSignLink = (
      await getEmbeddedSignLink(config, contractBoldId, signerEmail, `${origin}/quote/${portalToken}?signed=1`)
    ).signLink;
  } catch (e) {
    contractSignLink = null;
    console.warn("[e2e-setup] contract embed:", (e as Error).message);
  }
  if (!selectionSignLink) {
    try {
      selectionSignLink = (
        await getEmbeddedSignLink(
          config,
          selBody.boldsign_document_id,
          signerEmail,
          `${origin}/quote/${portalToken}?selection_signed=1`,
        )
      ).signLink;
    } catch (e) {
      console.warn("[e2e-setup] selection embed:", (e as Error).message);
    }
  }

  return jsonOk({
    ok: true,
    estimateId,
    estimateNumber,
    portalToken,
    contract: {
      docId: contractResult.docId,
      boldsignDocumentId: contractBoldId,
      signLink: contractSignLink,
      ...contractProbe,
    },
    selection: {
      boldsignDocumentId: selBody.boldsign_document_id,
      signLink: selectionSignLink,
      ...selectionProbe,
    },
  });
  } catch (e) {
    console.error("[e2e-setup] failed:", (e as Error).message, (e as Error).stack);
    return jsonOk({ ok: false, error: (e as Error).message }, 500);
  }
}

export async function handleOpsBoldsignGhostProof(
  request: Request,
  env: Env,
): Promise<Response> {
  const guard = requireSecret(request, env);
  if (guard) return guard;

  const config = await getBoldSignConfig(env);
  if (!config) {
    return jsonOk({ error: "BOLDSIGN_API_KEY not configured" }, 503);
  }

  const url = new URL(request.url);
  const signerEmail =
    url.searchParams.get("signer_email")?.trim() || "tony@homesolutionsar.com";
  const signerName = "Ghost Proof Test";
  const onlyPath = url.searchParams.get("path")?.trim() || "";
  const existingId = url.searchParams.get("document_id")?.trim() || "";

  // Re-scan an already-sent BoldSign doc (avoids another send + wait).
  if (existingId) {
    try {
      // Lightweight: form-field bounds + status only (no PDF download — saves API quota).
      if (url.searchParams.get("properties_only") === "1") {
        const propsRes = await fetch(
          `https://api.boldsign.com/v1/document/properties?documentId=${encodeURIComponent(existingId)}`,
          { headers: { "X-API-KEY": config.apiKey } },
        );
        if (!propsRes.ok) {
          return jsonOk(
            {
              error: `properties ${propsRes.status}: ${(await propsRes.text()).slice(0, 300)}`,
              documentId: existingId,
            },
            502,
          );
        }
        const full = (await propsRes.json()) as {
          status?: string;
          signerDetails?: Array<{
            signerEmail?: string;
            status?: string;
            formFields?: Array<{
              type?: string;
              fieldType?: string;
              name?: string;
              bounds?: { x?: number; y?: number; width?: number; height?: number };
              Bounds?: { X?: number; Y?: number; Width?: number; Height?: number };
            }>;
          }>;
        };
        const formFields = (full.signerDetails ?? []).flatMap((s) => s.formFields ?? []).map((f) => {
          const b = f.bounds ?? f.Bounds ?? {};
          return {
            type: f.type ?? f.fieldType ?? f.name,
            width: (b as { width?: number; Width?: number }).width ?? (b as { Width?: number }).Width,
            height:
              (b as { height?: number; Height?: number }).height ?? (b as { Height?: number }).Height,
            x: (b as { x?: number; X?: number }).x ?? (b as { X?: number }).X,
            y: (b as { y?: number; Y?: number }).y ?? (b as { Y?: number }).Y,
          };
        });
        const sig = formFields.find((f) => String(f.type ?? "").toLowerCase().includes("sign"));
        const fieldOk = !!sig && (sig.width ?? 0) >= 40 && (sig.height ?? 0) >= 10;
        return jsonOk({
          generated_at: new Date().toISOString(),
          path: "properties_only",
          documentId: existingId,
          boldSignStatus: full.status ?? null,
          formFields,
          signerDetails: (full.signerDetails ?? []).map((s) => ({
            email: s.signerEmail,
            status: s.status,
          })),
          signatureFieldOk: fieldOk,
          ok: fieldOk,
        });
      }

      const props = await getDocumentProperties(config, existingId);
      const pdf = await downloadSignedDocument(config, existingId);
      if (url.searchParams.get("return_pdf_b64") === "1") {
        const bytes = new Uint8Array(pdf);
        let binary = "";
        for (let i = 0; i < bytes.length; i++) binary += String.fromCharCode(bytes[i]);
        const pdf_b64 = btoa(binary);
        return jsonOk({
          generated_at: new Date().toISOString(),
          path: "pdf_b64",
          documentId: existingId,
          boldSignStatus: props?.status ?? null,
          pdfBytes: pdf.byteLength,
          pdf_b64,
        });
      }
      const scan = scanPdfGhosts(pdf);

      // Optional: probe whether getEmbeddedSignLink works (isolates widget 403s).
      let embed: { ok: boolean; status?: number; error?: string; hasLink?: boolean } | null =
        null;
      if (url.searchParams.get("embed_probe") === "1") {
        const signerEmail =
          url.searchParams.get("signer_email")?.trim() || "tony@homesolutionsar.com";
        const embedRes = await fetch(
          `https://api.boldsign.com/v1/document/getEmbeddedSignLink?documentId=${encodeURIComponent(existingId)}&signerEmail=${encodeURIComponent(signerEmail)}`,
          { headers: { "X-API-KEY": config.apiKey, accept: "application/json" } },
        );
        const bodyText = await embedRes.text().catch(() => "");
        let hasLink = false;
        try {
          hasLink = Boolean((JSON.parse(bodyText) as { signLink?: string }).signLink);
        } catch {
          /* not json */
        }
        embed = {
          ok: embedRes.ok && hasLink,
          status: embedRes.status,
          hasLink,
          error: embedRes.ok ? undefined : bodyText.slice(0, 400),
        };
      }

      let formFields: Array<{
        type?: string;
        width?: number;
        height?: number;
        x?: number;
        y?: number;
      }> = [];
      const propsRes = await fetch(
        `https://api.boldsign.com/v1/document/properties?documentId=${encodeURIComponent(existingId)}`,
        { headers: { "X-API-KEY": config.apiKey } },
      );
      if (propsRes.ok) {
        const full = (await propsRes.json()) as {
          status?: string;
          errorMessage?: string;
          signerDetails?: Array<{
            signerEmail?: string;
            status?: string;
            formFields?: Array<{
              type?: string;
              fieldType?: string;
              name?: string;
              bounds?: { x?: number; y?: number; width?: number; height?: number };
              Bounds?: { X?: number; Y?: number; Width?: number; Height?: number };
            }>;
          }>;
        };
        formFields = (full.signerDetails ?? []).flatMap((s) => s.formFields ?? []).map((f) => {
          const b = f.bounds ?? f.Bounds ?? {};
          return {
            type: f.type ?? f.fieldType ?? f.name,
            width: (b as { width?: number; Width?: number }).width ?? (b as { Width?: number }).Width,
            height:
              (b as { height?: number; Height?: number }).height ?? (b as { Height?: number }).Height,
            x: (b as { x?: number; X?: number }).x ?? (b as { X?: number }).X,
            y: (b as { y?: number; Y?: number }).y ?? (b as { Y?: number }).Y,
          };
        });
        return jsonOk({
          generated_at: new Date().toISOString(),
          path: "existing_document",
          documentId: existingId,
          boldSignStatus: full.status ?? props?.status ?? null,
          errorMessage: full.errorMessage ?? props?.errorMessage ?? null,
          pdfBytes: pdf.byteLength,
          ...scan,
          embed,
          formFields,
          signerDetails: (full.signerDetails ?? []).map((s) => ({
            email: s.signerEmail,
            status: s.status,
          })),
          ok: !scan.hasSignTag && !scan.hasDateTag && !scan.hasDocumentIdFooter,
        });
      }

      return jsonOk({
        generated_at: new Date().toISOString(),
        path: "existing_document",
        documentId: existingId,
        boldSignStatus: props?.status ?? null,
        pdfBytes: pdf.byteLength,
        ...scan,
        embed,
        formFields,
        ok: !scan.hasSignTag && !scan.hasDateTag && !scan.hasDocumentIdFooter,
      });
    } catch (e) {
      return jsonOk({ error: (e as Error).message, documentId: existingId }, 502);
    }
  }

  const r2Keys: Array<{ path: string; key: string; mode: "text_tags" | "template" }> = [
    {
      path: "estimate_sa_text_tags",
      key: "documents/templates/service-agreement.docx",
      mode: "text_tags",
    },
    {
      path: "estimate_selection_combined_text_tags",
      key: "documents/templates/selection-combined-approval.docx",
      mode: "text_tags",
    },
    {
      path: "job_lien_waiver_template_id",
      key: "documents/templates/lien-waiver-conditional.docx",
      mode: "template",
    },
    {
      path: "sub_agreement_text_tags",
      key: "documents/templates/subcontractor-agreement.docx",
      mode: "text_tags",
    },
  ];

  const selected = onlyPath
    ? r2Keys.filter((r) => r.path === onlyPath)
    : r2Keys.slice(0, 1); // default: one path to stay under subrequest limits
  if (onlyPath && selected.length === 0) {
    return jsonOk(
      { error: "unknown path", known: r2Keys.map((r) => r.path) },
      400,
    );
  }

  const results: GhostProofPathResult[] = [];

  for (const item of selected) {
    const row: GhostProofPathResult = {
      path: item.path,
      ok: false,
      hasSignTag: true,
      hasDateTag: true,
      hasDocumentIdFooter: true,
    };
    try {
      const obj = await env.FILES.get(item.key);
      if (!obj && item.mode === "text_tags") {
        row.error = `R2 missing ${item.key}`;
        results.push(row);
        continue;
      }

      let documentId: string;
      if (item.mode === "text_tags") {
        const bytes = await obj!.arrayBuffer();
        const send = await sendDocumentForSignature(config, {
          fileBlob: new Blob([bytes], {
            type: "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
          }),
          filename: `${item.path}.docx`,
          title: `[GHOST-PROOF] ${item.path}`,
          message: "Automated ghost-tag proof — revoke after scan.",
          signerEmail,
          signerName,
          useTextTags: true,
        });
        documentId = send.documentId;
      } else {
        const send = await sendDocumentForSignature(config, {
          fileBlob: new Blob(["unused"], { type: "application/octet-stream" }),
          filename: "unused.docx",
          title: `[GHOST-PROOF] ${item.path}`,
          message: "Automated ghost-tag proof — revoke after scan.",
          signerEmail,
          signerName,
          templateId: "7d6692c2-21e9-4ae9-ba2a-7f45c1f33eba",
          signerRole: "Client",
          roleIndex: 2,
        });
        documentId = send.documentId;
      }

      row.documentId = documentId;

      // BoldSign conversion is async — poll download only (few subrequests).
      let pdf: ArrayBuffer | null = null;
      let status: string | null | undefined = null;
      for (let attempt = 0; attempt < 10; attempt++) {
        await sleep(4000);
        try {
          pdf = await downloadSignedDocument(config, documentId);
          const props = await getDocumentProperties(config, documentId);
          status = props?.status ?? null;
          break;
        } catch {
          // still processing
        }
      }
      row.boldSignStatus = status;

      if (!pdf) {
        row.error = "download timed out";
        results.push(row);
        try {
          await revokeDocument(config, documentId, "ghost-proof cleanup");
        } catch {
          /* ignore */
        }
        continue;
      }

      const scan = scanPdfGhosts(pdf);
      row.hasSignTag = scan.hasSignTag;
      row.hasDateTag = scan.hasDateTag;
      row.hasDocumentIdFooter = scan.hasDocumentIdFooter;
      row.pdfBytes = pdf.byteLength;

      // Surface signature/date field bounds so we can catch 1pt-shrink regressions.
      const propsRes = await fetch(
        `https://api.boldsign.com/v1/document/properties?documentId=${encodeURIComponent(documentId)}`,
        { headers: { "X-API-KEY": config.apiKey } },
      );
      if (propsRes.ok) {
        const props = (await propsRes.json()) as {
          status?: string;
          signerDetails?: Array<{
            formFields?: Array<{
              type?: string;
              fieldType?: string;
              name?: string;
              bounds?: { x?: number; y?: number; width?: number; height?: number };
              Bounds?: { X?: number; Y?: number; Width?: number; Height?: number };
            }>;
          }>;
        };
        row.boldSignStatus = props.status ?? row.boldSignStatus;
        const fields = (props.signerDetails ?? []).flatMap((s) => s.formFields ?? []);
        (row as GhostProofPathResult & { formFields?: unknown }).formFields = fields.map((f) => {
          const b = f.bounds ?? f.Bounds ?? {};
          return {
            type: f.type ?? f.fieldType ?? f.name,
            width: (b as { width?: number; Width?: number }).width ?? (b as { Width?: number }).Width,
            height: (b as { height?: number; Height?: number }).height ?? (b as { Height?: number }).Height,
            x: (b as { x?: number; X?: number }).x ?? (b as { X?: number }).X,
            y: (b as { y?: number; Y?: number }).y ?? (b as { Y?: number }).Y,
          };
        });
        const sig = (row as { formFields?: Array<{ type?: string; width?: number; height?: number }> })
          .formFields?.find((f) =>
            String(f.type ?? "").toLowerCase().includes("sign"),
          );
        // Tiny signature boxes (height/width under ~20) indicate the 1pt shrink bug.
        if (sig && ((sig.width ?? 0) < 40 || (sig.height ?? 0) < 15)) {
          row.ok = false;
          row.error = `signature field too small: ${JSON.stringify(sig)}`;
        }
      }

      // Template-id path has no text tags in our upload; only Document ID matters.
      if (!row.error) {
        row.ok =
          item.mode === "template"
            ? !scan.hasDocumentIdFooter
            : !scan.hasSignTag && !scan.hasDateTag && !scan.hasDocumentIdFooter;
      }

      try {
        await revokeDocument(config, documentId, "ghost-proof cleanup");
      } catch (e) {
        row.error = `revoke: ${(e as Error).message}`;
      }
    } catch (e) {
      row.error = (e as Error).message;
    }
    results.push(row);
  }

  return jsonOk({
    generated_at: new Date().toISOString(),
    all_ok: results.every((r) => r.ok),
    results,
    note:
      "Scans raw PDF bytes for {{sign|, {{date|, and Document ID:. " +
      "Unsigned downloads are valid for ghost detection.",
  });
}
