/**
 * Public, token-gated quote delivery + Stripe webhook (Sprint 5).
 *
 * These endpoints are UNAUTHENTICATED — there is no Cloudflare Access and no
 * session. The estimate's `portal_token` is the only credential. An invalid or
 * expired token returns 404/410, never an internal error or a data leak.
 *
 * HARD RULE: sub-items NEVER appear in any public payload. Every public read
 * selects parent line-item columns only and shapes a deliberately narrow object
 * — there is no code path here that can reach estimate_sub_items.
 *
 *   GET  /api/public/quote/:token                 client-facing payload (+view track)
 *   POST /api/public/quote/:token/sign            capture digital signature
 *   POST /api/public/quote/:token/request-changes flag the request for follow-up
 *   POST /api/public/quote/:token/pay/intent      Stripe PaymentIntent (deposit + 3.5%)
 *   POST /api/public/quote/:token/pay/check       record check intent (no fee, no convert)
 *   POST /api/webhooks/stripe                      deposit succeeded → shared conversion
 *
 * The Stripe deposit is the automatic Won trigger: on payment_intent.succeeded
 * the webhook calls the SAME convertQuoteToJob() the manual "Mark as Won" modal
 * uses (src/lib/quote-to-job.ts) — one conversion path, never two.
 */

import type { Env } from "../env.js";
import { convertQuoteToJob, reverseJobConversion } from "../lib/quote-to-job.js";
import { assertQuoteSelectionsComplete, getQuoteSelectionProgress } from "./selections.js";
import { recordPayment } from "./payments.js";
import { triggerDealWon } from "../lib/wc/triggers.js";
import {
  triggerJobConversionNotifications,
  triggerNotification,
} from "../lib/notification-engine.js";
import { maybeAutoGenerateDocument } from "../lib/document-autotrigger.js";
import { depositFromSchedule } from "../lib/deposit-from-schedule.js";
import {
  estimateNeedsSignature,
  estimateSignatureComplete,
  estimateBoldsignEmbedReady,
  loadEstimateContractDoc,
  parseSignatureMeta,
  refreshEstimateContractSignatureStatus,
  refreshEstimateContractSignatureStatusWithRetry,
  resendEstimateContractForSigning,
  shouldSkipContractAutogen,
} from "../lib/estimate-contract-document.js";
import { scheduleWorkingAgreementGeneration } from "../lib/working-agreement.js";
import { getBoldSignConfig, getEmbeddedSignLink } from "../lib/boldsign.js";
import {
  convenienceFee as computeFee,
  createPaymentIntent,
  getStripeConfig,
  isConfigured,
  verifyWebhookDetailed,
} from "../lib/stripe.js";

// ─── helpers ─────────────────────────────────────────────────────────────────

function json(body: unknown, init: ResponseInit = {}): Response {
  const headers = new Headers(init.headers);
  headers.set("content-type", "application/json; charset=utf-8");
  headers.set("cache-control", "no-store");
  return new Response(JSON.stringify(body), { ...init, headers });
}

function err(status: number, error: string, details?: string): Response {
  return json({ error, details }, { status });
}

async function readJson(request: Request): Promise<Record<string, unknown> | null> {
  try {
    return (await request.json()) as Record<string, unknown>;
  } catch {
    return null;
  }
}

function str(v: unknown): string | null {
  if (v === null || v === undefined) return null;
  const s = String(v).trim();
  return s === "" ? null : s;
}

function round2(n: number): number {
  return Math.round(n * 100) / 100;
}

/** Audit a public (client/token) action — attributed to the client, not a user. */
async function logPublicAudit(
  env: Env,
  token: string,
  clientEmail: string | null,
  action: string,
  estimateId: string,
  details: unknown,
): Promise<void> {
  const actor = clientEmail ?? `portal:${token.slice(0, 8)}`;
  await env.DB.prepare(
    "INSERT INTO audit_logs (id, user_email, action, entity_type, entity_id, details, created_at) VALUES (?, ?, ?, ?, ?, ?, datetime('now'))",
  )
    .bind(crypto.randomUUID(), actor, action, "estimate", estimateId, JSON.stringify(details))
    .run();
}

interface EstimateRow {
  id: string;
  estimate_number: number | null;
  request_id: string | null;
  client_id: string | null;
  title: string | null;
  billing_model: string | null;
  status: string;
  subtotal: number | null;
  tax_amount: number | null;
  total: number | null;
  deposit_amount: number | null;
  valid_days: number | null;
  expiration_date: string | null;
  portal_token: string | null;
  include_reviews: number | null;
  review_ids: string | null;
  include_contract: number | null;
  contract_text: string | null;
  client_signature: string | null;
  signed_date: string | null;
  viewed_date: string | null;
  approved_date: string | null;
  sent_at: string | null;
  deposit_payment_method: string | null;
  deposit_method_selected_at: string | null;
}

interface QuoteContext {
  est: EstimateRow;
  client_name: string | null;
  client_email: string | null;
  client_phone: string | null;
  property_address: string | null;
  property_city: string | null;
  property_state: string | null;
  property_zip: string | null;
}

async function loadByToken(env: Env, token: string): Promise<QuoteContext | null> {
  const est = await env.DB.prepare(
    `SELECT id, estimate_number, request_id, client_id, title, billing_model, status,
            subtotal, tax_amount, total, deposit_amount, valid_days, expiration_date,
            portal_token, include_reviews, review_ids, include_contract, contract_text,
            client_signature, signed_date, viewed_date, approved_date, sent_at,
            deposit_payment_method, deposit_method_selected_at
     FROM estimates WHERE portal_token = ?`,
  )
    .bind(token)
    .first<EstimateRow>();
  if (!est) return null;

  const ctx = await env.DB.prepare(
    `SELECT c.name AS client_name, c.first_name AS c_first, c.last_name AS c_last,
            c.email AS client_email, c.phone AS client_phone,
            er.property_address, er.property_city, er.property_state, er.property_zip
     FROM estimates e
     LEFT JOIN clients c ON c.id = e.client_id
     LEFT JOIN estimate_requests er ON er.id = e.request_id
     WHERE e.id = ?`,
  )
    .bind(est.id)
    .first<Record<string, unknown>>();

  const clientName =
    [ctx?.c_first, ctx?.c_last].filter(Boolean).join(" ").trim() ||
    (ctx?.client_name as string) ||
    null;

  return {
    est,
    client_name: clientName,
    client_email: (ctx?.client_email as string) ?? null,
    client_phone: (ctx?.client_phone as string) ?? null,
    property_address: (ctx?.property_address as string) ?? null,
    property_city: (ctx?.property_city as string) ?? null,
    property_state: (ctx?.property_state as string) ?? null,
    property_zip: (ctx?.property_zip as string) ?? null,
  };
}

function isExpired(est: EstimateRow): boolean {
  if (!est.expiration_date) return false;
  // expiration_date is a YYYY-MM-DD date; the quote is valid through that day.
  const exp = new Date(`${est.expiration_date}T23:59:59Z`).getTime();
  return Number.isFinite(exp) && Date.now() > exp;
}

/**
 * Build the client-facing payload. PARENT LINE ITEMS ONLY — this function never
 * touches estimate_sub_items, and the SELECT below lists exact safe columns.
 */
async function publicPayload(env: Env, qc: QuoteContext, cfg: { publishableKey: string | null; configured: boolean }) {
  const e = qc.est;
  const total = round2(e.total ?? 0);

  const lineItems = (
    await env.DB.prepare(
      `SELECT id, sort_order, product_service, description, quantity, unit, unit_price, total, includes_note
       FROM estimate_line_items WHERE estimate_id = ? ORDER BY sort_order ASC`,
    )
      .bind(e.id)
      .all<{
        id: string;
        sort_order: number;
        product_service: string;
        description: string;
        quantity: number | null;
        unit: string | null;
        unit_price: number | null;
        total: number | null;
        includes_note: string | null;
      }>()
  ).results ?? [];

  const schedule = (
    await env.DB.prepare(
      `SELECT id, sort_order, description, percentage, fixed_amount, amount, is_deposit, trigger
       FROM payment_schedules WHERE estimate_id = ? ORDER BY sort_order ASC`,
    )
      .bind(e.id)
      .all<{
        id: string;
        sort_order: number;
        description: string;
        percentage: number | null;
        fixed_amount: number | null;
        amount: number | null;
        is_deposit: number | null;
        trigger: string | null;
      }>()
  ).results ?? [];

  // Selected reviews (social proof). Honors the builder's include_reviews flag
  // and selected ids; falls back to the top active reviews like the preview.
  let reviews: Array<Record<string, unknown>> = [];
  if ((e.include_reviews ?? 1) === 1) {
    let ids: string[] = [];
    if (e.review_ids) {
      try {
        const parsed = JSON.parse(e.review_ids);
        if (Array.isArray(parsed)) ids = parsed.map((x) => String(x));
      } catch {
        ids = e.review_ids.split(",").map((s) => s.trim()).filter(Boolean);
      }
    }
    if (ids.length > 0) {
      const placeholders = ids.map(() => "?").join(",");
      const rows = (
        await env.DB.prepare(
          `SELECT id, reviewer_name, rating, review_text, review_date, source
           FROM saved_reviews WHERE id IN (${placeholders}) AND is_active = 1`,
        )
          .bind(...ids)
          .all<Record<string, unknown>>()
      ).results ?? [];
      reviews = rows;
    } else {
      const rows = (
        await env.DB.prepare(
          `SELECT id, reviewer_name, rating, review_text, review_date, source
           FROM saved_reviews WHERE is_active = 1
           ORDER BY COALESCE(sort_order, 9999) ASC, created_at DESC LIMIT 3`,
        ).all<Record<string, unknown>>()
      ).results ?? [];
      reviews = rows;
    }
  }

  const includeContract = (e.include_contract ?? 1) === 1;
  const contractDoc = includeContract ? await loadEstimateContractDoc(env, e.id) : null;
  const sigMeta = contractDoc
    ? await refreshEstimateContractSignatureStatus(env, contractDoc)
    : {};
  const signatureRequired = estimateNeedsSignature(includeContract, contractDoc);
  const signatureComplete = estimateSignatureComplete(
    includeContract,
    e.client_signature,
    contractDoc,
  );
  const boldsignMode = !!sigMeta.boldsign_document_id;
  const selectionProgress = await getQuoteSelectionProgress(env, e.id);

  return {
    token: e.portal_token,
    estimate_number: e.estimate_number,
    status: e.status,
    expired: isExpired(e),
    title: e.title,
    billing_model: e.billing_model,
    company_name: "Columbus Home Solutions",
    client_name: qc.client_name,
    client_phone: qc.client_phone,
    property_address: qc.property_address,
    property_city: qc.property_city,
    property_state: qc.property_state,
    property_zip: qc.property_zip,
    subtotal: round2(e.subtotal ?? 0),
    tax_amount: round2(e.tax_amount ?? 0),
    total,
    deposit_amount: depositFromSchedule(schedule, total) || null,
    deposit_payment_method: e.deposit_payment_method ?? null,
    deposit_method_selected_at: e.deposit_method_selected_at ?? null,
    valid_days: e.valid_days ?? 7,
    sent_date: e.sent_at,
    viewed_date: e.viewed_date,
    expiration_date: e.expiration_date,
    signed: signatureComplete,
    client_signature: e.client_signature,
    signed_date: e.signed_date,
    approved_date: e.approved_date,
    include_contract: includeContract,
    contract_text: includeContract ? e.contract_text : null,
    signature_required: signatureRequired,
    signature_complete: signatureComplete,
    contract_signature_mode: !includeContract ? "none" : boldsignMode ? "boldsign" : "typed",
    signature_status: sigMeta.signature_status ?? (signatureComplete ? "completed" : "none"),
    signature_error: sigMeta.signature_error ?? null,
    contract_document_id: contractDoc?.id ?? null,
    selections_required: selectionProgress.required,
    selections_total: selectionProgress.total,
    selections_chosen: selectionProgress.chosen,
    selections_all_chosen: selectionProgress.all_chosen,
    selections_approved: selectionProgress.approved,
    selections_signature_pending: selectionProgress.signature_pending,
    selections_complete: selectionProgress.complete,
    convenience_fee_rate: 0.035,
    stripe_enabled: cfg.configured,
    stripe_publishable_key: cfg.publishableKey,
    // PARENT line items only — sub-items are intentionally absent.
    line_items: lineItems.map((li) => ({
      id: li.id,
      product_service: li.product_service,
      description: li.description,
      quantity: li.quantity,
      unit: li.unit,
      unit_price: li.unit_price,
      total: round2((li.quantity ?? 0) * (li.unit_price ?? 0)),
      includes_note: li.includes_note,
    })),
    payment_schedule: schedule.map((p) => ({
      id: p.id,
      description: p.description,
      percentage: p.percentage,
      amount:
        p.fixed_amount != null
          ? round2(p.fixed_amount)
          : p.percentage != null
            ? round2((p.percentage / 100) * total)
            : round2(p.amount ?? 0),
      is_deposit: (p.is_deposit ?? 0) === 1,
      trigger: p.trigger,
    })),
    reviews: reviews.map((r) => ({
      id: r.id,
      reviewer_name: r.reviewer_name,
      rating: r.rating,
      review_text: r.review_text,
      review_date: r.review_date,
      source: r.source,
    })),
  };
}

// ─── GET /api/public/quote/:token ─────────────────────────────────────────────

export async function handlePublicQuoteGet(env: Env, token: string): Promise<Response> {
  const qc = await loadByToken(env, token);
  if (!qc) return err(404, "not_found", "This quote link is invalid or no longer available.");

  // First load of a sent quote flips it to viewed + stamps viewed_date.
  if (qc.est.status === "sent") {
    const now = new Date().toISOString();
    await env.DB.prepare(
      "UPDATE estimates SET status = 'viewed', viewed_date = ?, updated_at = ? WHERE id = ?",
    )
      .bind(now, now, qc.est.id)
      .run();
    qc.est.status = "viewed";
    qc.est.viewed_date = now;
    await logPublicAudit(env, token, qc.client_email, "quote_viewed", qc.est.id, {
      estimate_number: qc.est.estimate_number,
    });
  }

  const cfg = await getStripeConfig(env);
  const payload = await publicPayload(env, qc, {
    publishableKey: cfg.publishableKey,
    configured: isConfigured(cfg),
  });
  return json({ quote: payload });
}

// ─── POST /api/public/quote/:token/sign ───────────────────────────────────────

export async function handlePublicQuoteSign(
  request: Request,
  env: Env,
  token: string,
): Promise<Response> {
  const qc = await loadByToken(env, token);
  if (!qc) return err(404, "not_found", "This quote link is invalid or no longer available.");
  const e = qc.est;

  if (isExpired(e)) {
    return err(410, "expired", "This quote has expired and can no longer be signed.");
  }
  if (!["sent", "viewed"].includes(e.status)) {
    return err(409, "invalid_state", `This quote can't be signed from status '${e.status}'.`);
  }
  const selectionBlock = await assertQuoteSelectionsComplete(env, e.id);
  if (selectionBlock) return selectionBlock;

  const includeContract = (e.include_contract ?? 1) === 1;
  const contractDoc = includeContract ? await loadEstimateContractDoc(env, e.id) : null;
  const sigMeta = contractDoc ? parseSignatureMeta(contractDoc.signature_data) : {};
  if (sigMeta.boldsign_document_id) {
    return err(
      409,
      "use_boldsign",
      "Please sign using the electronic signature link on this page.",
    );
  }

  const body = await readJson(request);
  const signature = str(body?.signature);
  if (!signature) return err(400, "bad_request", "A typed signature (full name) is required.");
  const signedDate = str(body?.date) ?? new Date().toISOString().slice(0, 10);

  const now = new Date().toISOString();
  await env.DB.prepare(
    `UPDATE estimates
        SET client_signature = ?, signed_date = ?,
            status = CASE WHEN status IN ('sent','viewed') THEN 'signed' ELSE status END,
            updated_at = ?
      WHERE id = ?`,
  )
    .bind(signature, signedDate, now, e.id)
    .run();

  await logPublicAudit(env, token, qc.client_email, "quote_signed", e.id, {
    signature,
    signed_date: signedDate,
  });

  const reloaded = await loadByToken(env, token);
  const cfg = await getStripeConfig(env);
  const payload = await publicPayload(env, reloaded!, {
    publishableKey: cfg.publishableKey,
    configured: isConfigured(cfg),
  });
  return json({ quote: payload });
}

// ─── GET /api/public/quote/:token/sign-link ───────────────────────────────────

export async function handlePublicQuoteSignLink(
  request: Request,
  env: Env,
  token: string,
): Promise<Response> {
  const qc = await loadByToken(env, token);
  if (!qc) return err(404, "not_found", "This quote link is invalid or no longer available.");
  const e = qc.est;

  if (isExpired(e)) {
    return err(410, "expired", "This quote has expired and can no longer be signed.");
  }
  if ((e.include_contract ?? 1) !== 1) {
    return err(400, "no_contract", "This quote does not include a contract to sign.");
  }
  const selectionBlock = await assertQuoteSelectionsComplete(env, e.id);
  if (selectionBlock) return selectionBlock;

  const contractDoc = await loadEstimateContractDoc(env, e.id);
  if (!contractDoc) {
    return err(404, "contract_not_found", "Contract document is not ready yet. Please contact us.");
  }

  const meta = parseSignatureMeta(contractDoc.signature_data);
  if (!meta.boldsign_document_id || !meta.signer_email) {
    return err(400, "typed_signature", "This quote uses in-page signature — no BoldSign link available.");
  }
  if (meta.signature_status === "completed" || (contractDoc.is_signed ?? 0) === 1) {
    return err(409, "already_signed", "This agreement is already signed.");
  }

  const config = await getBoldSignConfig(env);
  if (!config) return err(503, "boldsign_unconfigured", "E-signature is not configured.");

  const origin = new URL(request.url).origin;
  const redirectUrl = `${origin}/quote/${token}?signed=1`;

  let activeMeta = await refreshEstimateContractSignatureStatus(env, contractDoc);
  let activeDoc = contractDoc;

  // BoldSign document/send is async: SendFailed leaves an ID that 403s on embed link.
  if (activeMeta.signature_status === "failed") {
    const resent = await resendEstimateContractForSigning(env, e.id, "quote-sign-link-resend");
    if (!resent) {
      return err(
        502,
        "signature_resend_failed",
        "Could not re-send the service agreement. Please contact us for a fresh quote link.",
      );
    }
    activeDoc = resent.contractDoc;
    activeMeta = await refreshEstimateContractSignatureStatusWithRetry(env, activeDoc);
  }

  if (activeMeta.signature_status === "pending") {
    activeMeta = await refreshEstimateContractSignatureStatusWithRetry(env, activeDoc);
  }

  if (activeMeta.signature_status === "pending") {
    return err(
      409,
      "signature_pending",
      "Your agreement is being prepared. Please wait a few seconds and try again.",
    );
  }

  if (activeMeta.signature_status === "failed") {
    return err(
      502,
      "signature_failed",
      activeMeta.signature_error ??
        "Could not prepare your service agreement for signing. Please try again or contact us.",
    );
  }

  if (!estimateBoldsignEmbedReady(activeMeta)) {
    return err(
      409,
      "signature_not_ready",
      `Agreement is not ready to sign yet (status: ${activeMeta.signature_status ?? "unknown"}).`,
    );
  }

  try {
    const link = await getEmbeddedSignLink(
      config,
      activeMeta.boldsign_document_id!,
      activeMeta.signer_email!,
      redirectUrl,
    );
    return json({ sign_link: link.signLink, signature_status: activeMeta.signature_status ?? "sent" });
  } catch (signErr) {
    const msg = (signErr as Error).message;
    if (msg.includes("Invalid Document ID") || msg.includes("403")) {
      const resent = await resendEstimateContractForSigning(env, e.id, "quote-sign-link-403-resend");
      if (!resent || !estimateBoldsignEmbedReady(resent.meta)) {
        return err(502, "boldsign_error", msg);
      }
      try {
        const link = await getEmbeddedSignLink(
          config,
          resent.meta.boldsign_document_id!,
          resent.meta.signer_email!,
          redirectUrl,
        );
        return json({ sign_link: link.signLink, signature_status: resent.meta.signature_status ?? "sent" });
      } catch (retryErr) {
        return err(502, "boldsign_error", (retryErr as Error).message);
      }
    }
    return err(502, "boldsign_error", msg);
  }
}

// ─── POST /api/public/quote/:token/request-changes ────────────────────────────

export async function handlePublicQuoteRequestChanges(
  request: Request,
  env: Env,
  token: string,
): Promise<Response> {
  const qc = await loadByToken(env, token);
  if (!qc) return err(404, "not_found", "This quote link is invalid or no longer available.");
  const e = qc.est;

  const body = await readJson(request);
  const message = str(body?.message);

  // Flip the linked request to follow_up so it surfaces for Tony to act on.
  // The client never edits the estimate — this only logs intent + flags it.
  if (e.request_id) {
    const now = new Date().toISOString();
    await env.DB.prepare(
      `UPDATE estimate_requests
       SET status = CASE WHEN status IN ('won','lost') THEN status ELSE 'follow_up' END,
           updated_at = ?
       WHERE id = ?`,
    )
      .bind(now, e.request_id)
      .run();
  }

  await logPublicAudit(env, token, qc.client_email, "quote_changes_requested", e.id, {
    request_id: e.request_id,
    message,
  });

  return json({
    ok: true,
    message:
      "Thanks — we've let the team know you'd like some changes. Tony will reach out to you shortly.",
  });
}

// ─── POST /api/public/quote/:token/pay/check|cash ─────────────────────────────
// Intent only — records cash/check preference, notifies Tony, does NOT create a job.

const OFFLINE_DEPOSIT_METHODS = new Set(["check", "cash"]);

export async function handlePublicQuotePayCheck(
  request: Request,
  env: Env,
  token: string,
  exec?: { waitUntil: (p: Promise<unknown>) => void },
): Promise<Response> {
  return recordOfflineDepositIntent(request, env, token, "check", exec);
}

export async function handlePublicQuotePayCash(
  request: Request,
  env: Env,
  token: string,
  exec?: { waitUntil: (p: Promise<unknown>) => void },
): Promise<Response> {
  return recordOfflineDepositIntent(request, env, token, "cash", exec);
}

async function recordOfflineDepositIntent(
  request: Request,
  env: Env,
  token: string,
  defaultMethod: "cash" | "check",
  exec?: { waitUntil: (p: Promise<unknown>) => void },
): Promise<Response> {
  const qc = await loadByToken(env, token);
  if (!qc) return err(404, "not_found", "This quote link is invalid or no longer available.");
  const e = qc.est;

  if (isExpired(e)) {
    return err(410, "expired", "This quote has expired. Please contact us for an updated quote.");
  }
  if (e.status === "approved" || e.approved_date) {
    return err(409, "already_paid", "This deposit has already been recorded. Thank you!");
  }
  const selectionBlock = await assertQuoteSelectionsComplete(env, e.id);
  if (selectionBlock) return selectionBlock;
  const includeContract = (e.include_contract ?? 1) === 1;
  const contractDoc = includeContract ? await loadEstimateContractDoc(env, e.id) : null;
  if (!estimateSignatureComplete(includeContract, e.client_signature, contractDoc)) {
    return err(409, "signature_required", "Please sign the service agreement before arranging payment.");
  }

  let method = defaultMethod;
  try {
    const body = (await request.json()) as { method?: string };
    const m = String(body?.method ?? "").toLowerCase();
    if (OFFLINE_DEPOSIT_METHODS.has(m)) method = m as "cash" | "check";
  } catch {
    /* no body — use route default */
  }

  const settings = await env.DB.prepare(
    "SELECT key, value FROM system_settings WHERE key IN ('company_name','company_address')",
  ).all<{ key: string; value: string }>();
  const sm: Record<string, string> = {};
  for (const r of settings.results ?? []) sm[r.key] = r.value;

  const estLabel = `EST-${String(e.estimate_number ?? 0).padStart(3, "0")}`;
  const checkSchedule = (
    await env.DB.prepare(
      "SELECT is_deposit, fixed_amount, percentage, amount FROM payment_schedules WHERE estimate_id = ? ORDER BY sort_order ASC",
    )
      .bind(e.id)
      .all<{ is_deposit: number | null; fixed_amount: number | null; percentage: number | null; amount: number | null }>()
  ).results ?? [];
  const checkDeposit = depositFromSchedule(checkSchedule, round2(e.total ?? 0));
  const depositDisplay =
    checkDeposit > 0
      ? new Intl.NumberFormat("en-US", { style: "currency", currency: "USD" }).format(checkDeposit)
      : "the deposit amount";

  const now = new Date().toISOString();
  await env.DB.prepare(
    `UPDATE estimates
        SET deposit_payment_method = ?, deposit_method_selected_at = ?, updated_at = ?
      WHERE id = ?`,
  )
    .bind(method, now, now, e.id)
    .run();

  await logPublicAudit(env, token, qc.client_email, "quote_deposit_method_selected", e.id, {
    deposit_amount: checkDeposit,
    estimate_number: e.estimate_number,
    method,
  });

  const adminPath = e.request_id
    ? `/estimating/${e.request_id}/estimate`
    : `/estimates/${e.id}`;
  const methodLabel = method === "cash" ? "Cash" : "Check";
  await triggerNotification(
    env,
    "deposit_method_selected",
    {
      clientId: e.client_id,
      estimateId: e.id,
      estimateRequestId: e.request_id,
      instanceKey: `${method}:${now.slice(0, 16)}`,
      linkPath: adminPath,
      merge: {
        deposit_method: methodLabel,
        estimate_label: estLabel,
        deposit_amount: depositDisplay,
        estimate_admin_link: `https://dashboard.homesolutionsar.com${adminPath}`,
        client_name: qc.client_name ?? "A client",
      },
    },
    { exec },
  );

  const thanks =
    method === "cash"
      ? "Thanks — we'll follow up to collect your cash deposit and get your job scheduled."
      : "Thanks — we'll follow up once your check deposit is received and get your job scheduled.";

  return json({
    ok: true,
    method,
    deposit_amount: checkDeposit > 0 ? checkDeposit : null,
    convenience_fee: 0,
    reference: estLabel,
    message: thanks,
    instructions:
      method === "check"
        ? {
            payable_to: sm.company_name ?? "Columbus Home Solutions, LLC",
            mailing_address: sm.company_address ?? "",
            memo: `Deposit — ${estLabel}`,
            note: "No convenience fee applies to check payments. Your project is scheduled once we confirm the deposit has cleared.",
          }
        : {
            payable_to: sm.company_name ?? "Columbus Home Solutions, LLC",
            mailing_address: null,
            memo: null,
            note: "No convenience fee applies to cash. Tony will arrange collection with you — no job is created until the deposit is confirmed received.",
          },
  });
}

// ─── POST /api/public/quote/:token/pay/intent ─────────────────────────────────

export async function handlePublicQuotePayIntent(
  _request: Request,
  env: Env,
  token: string,
): Promise<Response> {
  const qc = await loadByToken(env, token);
  if (!qc) return err(404, "not_found", "This quote link is invalid or no longer available.");
  const e = qc.est;

  if (isExpired(e)) {
    return err(410, "expired", "This quote has expired and can no longer be paid.");
  }
  const selectionBlock = await assertQuoteSelectionsComplete(env, e.id);
  if (selectionBlock) return selectionBlock;
  const includeContract = (e.include_contract ?? 1) === 1;
  const contractDoc = includeContract ? await loadEstimateContractDoc(env, e.id) : null;
  if (!estimateSignatureComplete(includeContract, e.client_signature, contractDoc)) {
    return err(409, "signature_required", "Please sign the service agreement before paying the deposit.");
  }
  const paySchedule = (
    await env.DB.prepare(
      "SELECT is_deposit, fixed_amount, percentage, amount FROM payment_schedules WHERE estimate_id = ? ORDER BY sort_order ASC",
    )
      .bind(e.id)
      .all<{ is_deposit: number | null; fixed_amount: number | null; percentage: number | null; amount: number | null }>()
  ).results ?? [];
  const deposit = depositFromSchedule(paySchedule, round2(e.total ?? 0));
  if (deposit <= 0) {
    return err(400, "no_deposit", "No deposit milestone is configured for this quote.");
  }

  const cfg = await getStripeConfig(env);
  const fee = computeFee(deposit, 0.035);
  const totalCharge = round2(deposit + fee);

  const intent = await createPaymentIntent(cfg, {
    amountCents: Math.round(totalCharge * 100),
    description: `Deposit — EST-${String(e.estimate_number ?? 0).padStart(3, "0")}`,
    metadata: {
      kind: "deposit",
      estimate_id: e.id,
      request_id: e.request_id ?? "",
      token,
      deposit: String(deposit),
      convenience_fee: String(fee),
    },
  });

  if (!intent.ok) {
    return err(intent.status, intent.error, intent.details);
  }

  await logPublicAudit(env, token, qc.client_email, "quote_payment_intent", e.id, {
    payment_intent_id: intent.id,
    deposit,
    convenience_fee: fee,
    total_charge: totalCharge,
  });

  return json({
    ok: true,
    client_secret: intent.client_secret,
    publishable_key: cfg.publishableKey,
    deposit_amount: deposit,
    convenience_fee: fee,
    total_charge: totalCharge,
    disclosure: `Deposit: ${usd(deposit)} + Convenience Fee (3.5%): ${usd(fee)} = Total: ${usd(totalCharge)}`,
  });
}

function usd(n: number): string {
  return new Intl.NumberFormat("en-US", { style: "currency", currency: "USD" }).format(n);
}

// ─── POST /api/webhooks/stripe ────────────────────────────────────────────────

export async function handleStripeWebhook(request: Request, env: Env, ctx: ExecutionContext): Promise<Response> {
  const cfg = await getStripeConfig(env);
  const payload = await request.text();
  const sig = request.headers.get("stripe-signature");

  const verified = await verifyWebhookDetailed(payload, sig, cfg.webhookSecret);
  if (!verified.ok) {
    // Safe to log: reason only, never the secret or full signature.
    await logPublicAudit(env, "", null, "stripe_webhook_verify_failed", "stripe", {
      reason: verified.reason,
      has_sig_header: !!sig,
      has_webhook_secret: !!cfg.webhookSecret,
      payload_bytes: payload.length,
    });
    const details =
      verified.reason === "timestamp_outside_tolerance"
        ? "Webhook timestamp is outside the allowed window (5 minutes). Use a fresh delivery or check server clock skew."
        : verified.reason === "missing_header_or_secret"
          ? "Missing Stripe-Signature header or STRIPE_WEBHOOK_SECRET on the Worker."
          : verified.reason === "signature_mismatch"
            ? "Webhook signature verification failed. Confirm the endpoint signing secret matches STRIPE_WEBHOOK_SECRET (Dashboard → Webhooks → Reveal secret, not the CLI listen secret)."
            : "Webhook signature verification failed.";
    return err(400, "invalid_signature", details);
  }
  const event = verified.event;

  const type = String(event.type ?? "");
  const obj = ((event.data as Record<string, unknown>)?.object ?? {}) as Record<string, unknown>;
  const metadata = (obj.metadata ?? {}) as Record<string, string>;

  // Reverse-conversion triggers (refund / chargeback) — flag-and-preserve.
  if (type === "charge.refunded" || type === "charge.dispute.created") {
    return handleStripeReversal(env, type, obj);
  }

  // Only succeeded PaymentIntents drive payment recording / conversion.
  if (type !== "payment_intent.succeeded") {
    await logPublicAudit(env, "", null, "stripe_webhook_ignored", "stripe", { ignored: type });
    return json({ received: true, ignored: type });
  }

  // Sprint 9: invoice payments. A PaymentIntent created from the public pay page
  // carries metadata.invoice_id and routes here (NOT through quote conversion).
  if (metadata.invoice_id) {
    return handleInvoicePaymentWebhook(env, obj, metadata, ctx);
  }

  // Deposit branch (Sprint 5) — unchanged single conversion path.
  if (metadata.kind !== "deposit") {
    await logPublicAudit(env, "", null, "stripe_webhook_ignored", "stripe", {
      ignored: "non_deposit_intent",
      payment_intent_id: obj.id ?? null,
      metadata_keys: Object.keys(metadata),
    });
    return json({ received: true, ignored: "non_deposit_intent" });
  }

  const requestId = metadata.request_id;
  const estimateId = metadata.estimate_id;
  const token = metadata.token ?? "";
  const deposit = Number(metadata.deposit);
  const fee = Number(metadata.convenience_fee);
  const stripePaymentId = String(obj.id ?? "");

  if (!requestId || !Number.isFinite(deposit) || deposit <= 0) {
    // Ack so Stripe stops retrying a malformed intent, but record nothing.
    await logPublicAudit(env, token, null, "stripe_webhook_ignored", estimateId ?? "stripe", {
      ignored: "missing_metadata",
      payment_intent_id: stripePaymentId,
      request_id: requestId || null,
      deposit: metadata.deposit ?? null,
    });
    return json({ received: true, ignored: "missing_metadata" });
  }

  // Best-effort: pull Stripe's processing fee if the charge expanded it.
  let stripeFee: number | null = null;
  try {
    const charges = (obj.charges as { data?: Array<Record<string, unknown>> })?.data;
    const bt = charges?.[0]?.balance_transaction as { fee?: number } | undefined;
    if (bt && typeof bt.fee === "number") stripeFee = round2(bt.fee / 100);
  } catch {
    stripeFee = null;
  }

  // CONVERGENCE: the same engine the manual "Mark as Won" modal calls. The only
  // difference is the source of the payment data. Idempotent — a retry on a
  // fully-converted request returns {idempotent:true} and is ack'd 200 below; a
  // bare/unconverted stub (e.g. production job #100) gets COMPLETED in place.
  const outcome = await convertQuoteToJob(
    env,
    requestId,
    {
      amount: deposit,
      method: "stripe",
      reference: stripePaymentId || null,
      convenienceFee: Number.isFinite(fee) ? fee : null,
      stripeFee,
      stripePaymentId: stripePaymentId || null,
    },
    null,
  );

  if (!outcome.ok) {
    // Log and ack (200) — returning non-2xx makes Stripe retry indefinitely.
    await logPublicAudit(env, token, null, "quote_deposit_failed", estimateId ?? requestId, {
      error: outcome.error,
      details: outcome.details,
    });
    return json({ received: true, conversion_error: outcome.error });
  }

  if (outcome.idempotent) {
    await logPublicAudit(env, token, null, "stripe_webhook_idempotent", estimateId ?? requestId, {
      payment_intent_id: stripePaymentId,
      request_id: requestId,
      job_id: outcome.jobId,
    });
    return json({ received: true, idempotent: true });
  }

  await logPublicAudit(env, token, null, "quote_deposit_paid", estimateId ?? requestId, {
    job_id: outcome.jobId,
    job_number: outcome.jobNumber,
    payment_id: outcome.paymentId,
    deposit,
    convenience_fee: Number.isFinite(fee) ? fee : null,
    stripe_payment_id: stripePaymentId,
  });

  // Job-scoped audit entry (system/token-attributed) for the Job Detail
  // Activity tab — mirrors the manual Won path's job_created log.
  await env.DB.prepare(
    "INSERT INTO audit_logs (id, user_email, action, entity_type, entity_id, details, created_at) VALUES (?, ?, ?, 'job', ?, ?, datetime('now'))",
  )
    .bind(
      crypto.randomUUID(),
      "system@stripe-webhook",
      "job_created",
      outcome.jobId,
      JSON.stringify({ from_request: requestId, job_number: outcome.jobNumber, deposit_method: "stripe" }),
    )
    .run();

  // WC closed-deal count + New Sales value track the contract total.
  triggerDealWon(env, outcome.jobId, outcome.total);

  // Notifications: deposit receipt + welcome-portal emails (immediate,
  // idempotent on the job id — a Stripe webhook redelivery never double-sends).
  // Fired AFTER the conversion succeeded; the verify/branch/200 logic above is
  // untouched.
  await triggerJobConversionNotifications(env, outcome.jobId);

  // Sprint 20 — Auto-generate contract document. Job is created at deposit_paid
  // so this is the equivalent of the deposit_paid status trigger for portal conversions.
  // Non-blocking: doc gen failure must never affect the webhook 200 response.
  {
    const jobForBilling = await env.DB.prepare(
      "SELECT billing_model FROM jobs WHERE id = ?",
    )
      .bind(outcome.jobId)
      .first<{ billing_model: string | null }>();
    const contractTemplate =
      (jobForBilling?.billing_model ?? "fixed_price") === "cost_plus"
        ? "cost_plus_agreement"
        : "service_agreement";
    const skipAutogen = await shouldSkipContractAutogen(env, outcome.jobId, contractTemplate);
    if (skipAutogen) {
      console.log(
        `[AUTOTRIGGER] public-quote stripe deposit — skip ${contractTemplate} (estimate contract already signed)`,
      );
    } else {
      console.log(`[AUTOTRIGGER] public-quote stripe deposit — jobId=${outcome.jobId} template=${contractTemplate}`);
      ctx.waitUntil(
        maybeAutoGenerateDocument(env, {
          jobId: outcome.jobId,
          templateType: contractTemplate,
          triggerEvent: "job_deposit_paid",
        }).catch((e) =>
          console.error("[public-quote] doc auto-gen (deposit_paid) failed:", (e as Error).message),
        ),
      );
    }
  }

  scheduleWorkingAgreementGeneration(env, outcome.jobId, ctx);

  return json({ received: true, job_id: outcome.jobId, job_number: outcome.jobNumber });
}

/** Best-effort extraction of Stripe's processing fee (cents → dollars). */
function stripeFeeFromObject(obj: Record<string, unknown>): number | null {
  try {
    const charges = (obj.charges as { data?: Array<Record<string, unknown>> })?.data;
    const bt = charges?.[0]?.balance_transaction as { fee?: number } | undefined;
    if (bt && typeof bt.fee === "number") return round2(bt.fee / 100);
  } catch {
    /* ignore */
  }
  return null;
}

/** Map the Stripe payment-method type to our enum. */
function methodFromObject(obj: Record<string, unknown>): string {
  try {
    const charges = (obj.charges as { data?: Array<Record<string, unknown>> })?.data;
    const pmType = (charges?.[0]?.payment_method_details as { type?: string } | undefined)?.type;
    if (pmType === "us_bank_account" || pmType === "ach_debit") return "ach";
  } catch {
    /* ignore */
  }
  return "credit_card";
}

/**
 * Invoice payment branch (Sprint 9). The PaymentIntent's metadata carries
 * invoice_id / job_id / client_id / base_amount / convenience_fee. We route the
 * money through the SAME recordPayment() the manual route uses — idempotent on
 * the PaymentIntent id, recomputes invoice status, fires the receipt. Always
 * ack 200 so Stripe stops retrying.
 */
async function handleInvoicePaymentWebhook(
  env: Env,
  obj: Record<string, unknown>,
  metadata: Record<string, string>,
  ctx: ExecutionContext,
): Promise<Response> {
  const stripePaymentId = String(obj.id ?? "");
  const invoiceId = metadata.invoice_id;
  // base_amount is the invoice balance; the amount Stripe charged includes the
  // 3.5% convenience fee. We record the BASE against the invoice and track the
  // fee separately (revenue, never folded into contract value).
  const baseAmount = Number(metadata.base_amount ?? metadata.amount);
  const fee = Number(metadata.convenience_fee);

  if (!invoiceId || !Number.isFinite(baseAmount) || baseAmount <= 0) {
    await logPublicAudit(env, "", null, "stripe_webhook_ignored", "stripe", {
      ignored: "invoice_missing_metadata",
      payment_intent_id: stripePaymentId,
      invoice_id: invoiceId ?? null,
    });
    return json({ received: true, ignored: "invoice_missing_metadata" });
  }

  const result = await recordPayment(env, {
    jobId: metadata.job_id ?? null,
    invoiceId,
    clientId: metadata.client_id ?? null,
    amount: round2(baseAmount),
    method: methodFromObject(obj),
    convenienceFee: Number.isFinite(fee) ? round2(fee) : null,
    stripeFee: stripeFeeFromObject(obj),
    stripePaymentId,
    ctx,
  });

  await logPublicAudit(
    env,
    metadata.token ?? "",
    null,
    result.created ? "invoice_payment_recorded" : "stripe_webhook_idempotent",
    invoiceId,
    {
      payment_id: result.paymentId,
      invoice_id: invoiceId,
      invoice_status: result.invoiceStatus,
      base_amount: round2(baseAmount),
      convenience_fee: Number.isFinite(fee) ? round2(fee) : null,
      stripe_payment_id: stripePaymentId,
    },
  );

  return json({
    received: true,
    idempotent: !result.created,
    payment_id: result.paymentId,
    invoice_status: result.invoiceStatus,
  });
}

/**
 * Reverse-conversion via Stripe (refund / dispute). The event object is a CHARGE
 * whose payment_intent links back to the deposit we recorded at conversion. We
 * find the job by that PaymentIntent id and call reverseJobConversion() — the
 * same flag-and-preserve engine the manual O-only action uses. Always ack 200.
 */
async function handleStripeReversal(
  env: Env,
  type: string,
  obj: Record<string, unknown>,
): Promise<Response> {
  const piId = String(obj.payment_intent ?? obj.id ?? "");
  const reason = type === "charge.dispute.created" ? "stripe_dispute" : "stripe_refund";

  // The deposit payment carries the PaymentIntent id; that locates the job.
  const pay = piId
    ? await env.DB.prepare("SELECT job_id FROM payments WHERE stripe_payment_id = ?")
        .bind(piId)
        .first<{ job_id: string | null }>()
    : null;

  if (!pay?.job_id) {
    await logPublicAudit(env, "", null, "stripe_webhook_ignored", "stripe", {
      ignored: "reversal_no_job",
      event: type,
      payment_intent_id: piId || null,
    });
    return json({ received: true, ignored: "reversal_no_job" });
  }

  const outcome = await reverseJobConversion(env, pay.job_id, reason, "system@stripe-webhook");
  if (!outcome.ok) {
    await logPublicAudit(env, "", null, "job_conversion_reverse_failed", pay.job_id, {
      event: type,
      error: outcome.error,
      details: outcome.details,
    });
    return json({ received: true, reverse_error: outcome.error });
  }

  await logPublicAudit(env, "", null, "job_conversion_reversed", pay.job_id, {
    event: type,
    reason,
    voided_invoices: outcome.voidedInvoices,
    already_reversed: outcome.alreadyReversed,
  });
  return json({ received: true, reversed: true, job_id: pay.job_id, voided_invoices: outcome.voidedInvoices });
}
