import { describe, it, expect } from "vitest";

/** Mirrors once-per-job dedup in maybeAutoGenerateDocument. */
function shouldBlockDuplicate(opts: {
  templateType: string;
  existingRelatedIds: Array<string | null>;
  newRelatedId: string | null;
}): boolean {
  const oncePerJob =
    opts.templateType === "lien_waiver_conditional" ||
    opts.templateType === "warranty_certificate";
  if (oncePerJob) return opts.existingRelatedIds.length > 0;
  return opts.existingRelatedIds.some((id) => id === opts.newRelatedId);
}

describe("completion document idempotency", () => {
  it("blocks a second conditional lien waiver for the same job even with a new payment id", () => {
    expect(
      shouldBlockDuplicate({
        templateType: "lien_waiver_conditional",
        existingRelatedIds: ["payment-1"],
        newRelatedId: "payment-2",
      }),
    ).toBe(true);
  });

  it("still allows per-related-record docs for other template types", () => {
    expect(
      shouldBlockDuplicate({
        templateType: "change_order",
        existingRelatedIds: ["co-1"],
        newRelatedId: "co-2",
      }),
    ).toBe(false);
  });

  it("blocks a second warranty certificate for the same job", () => {
    expect(
      shouldBlockDuplicate({
        templateType: "warranty_certificate",
        existingRelatedIds: [null],
        newRelatedId: null,
      }),
    ).toBe(true);
  });
});
