import { describe, expect, it } from "vitest";
import { readFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import {
  IMAGE_GEN_MODEL,
  assembleImagePrompt,
  decodeBase64Bytes,
  extractGeminiImage,
  imageGenConfigured,
  imageGenEndpoint,
  resolveGoogleServiceAccount,
  resolveImageGenModel,
  sanitizeImagePrompt,
  socialImageKey,
} from "../src/lib/image-gen.js";
import { decideImageGenProbe, parseProbeState, runImageGenSelfTest } from "../src/lib/image-gen-probe.js";
import type { Env } from "../src/env.js";

const repoRoot = join(dirname(fileURLToPath(import.meta.url)), "..");

describe("Gemini image-gen migration", () => {
  it("targets the confirmed Vertex Gemini Flash Image model via generateContent", () => {
    expect(IMAGE_GEN_MODEL).toBe("gemini-2.5-flash-image");
    const src = readFileSync(join(repoRoot, "src/lib/image-gen.ts"), "utf8");
    expect(src).toContain("resolveImageGenModel");
    expect(src).toContain(":generateContent");
    expect(src).toContain("responseModalities");
    expect(src).toContain('aspectRatio: "1:1"');
    expect(src).toMatch(/Vertex generative model IDs are retired periodically/);
    expect(src).not.toMatch(/imagen-3\.0|imagen-4\.0|:predict|bytesBase64Encoded/);
  });

  it("strips text-overlay instructions that produce garbled copy", () => {
    const cleaned = sanitizeImagePrompt(
      'Kitchen remodel with text overlay "After" and a watermark logo banner',
    );
    expect(cleaned.toLowerCase()).not.toMatch(/\b(text|watermark|logo|banner)\b/);
    expect(cleaned).not.toContain("After");
  });

  it("appends the photorealistic no-text style suffix after sanitization", () => {
    const assembled = assembleImagePrompt("Kitchen remodel with text overlay");
    expect(assembled).toMatch(/Photorealistic, natural lighting, professional quality/);
    expect(assembled).toMatch(/No text, no words/);
    expect(assembled.toLowerCase()).not.toMatch(/text overlay/);
  });

  it("reads camelCase inlineData from generateContent (transcribe convention)", () => {
    const extracted = extractGeminiImage({
      candidates: [
        {
          content: {
            parts: [
              { text: "here is the image" },
              { inlineData: { data: "Zm9v", mimeType: "image/png" } },
            ],
          },
        },
      ],
    });
    expect(extracted).toEqual({ b64: "Zm9v", mimeType: "image/png" });
  });

  it("falls back to snake_case inline_data if Vertex returns that shape", () => {
    const extracted = extractGeminiImage({
      candidates: [
        {
          content: {
            parts: [{ inline_data: { data: "YmFy", mime_type: "image/jpeg" } }],
          },
        },
      ],
    });
    expect(extracted).toEqual({ b64: "YmFy", mimeType: "image/jpeg" });
  });

  it("returns null when no image part is present", () => {
    expect(extractGeminiImage({ candidates: [{ content: { parts: [{ text: "nope" }] } }] })).toBeNull();
  });

  it("decodes base64 with atob (Workers-safe, no Buffer)", () => {
    const bytes = decodeBase64Bytes("Zm9v"); // "foo"
    expect(Array.from(bytes)).toEqual([102, 111, 111]);
  });

  it("stores generated bytes under a deterministic social-images key", () => {
    expect(socialImageKey("post-123")).toBe("social-images/post-123.png");
  });

  it("resolveGoogleServiceAccount still gates on the three Vertex secrets", () => {
    const full = {
      GOOGLE_CLIENT_EMAIL: "sa@example.com",
      GOOGLE_PRIVATE_KEY: "-----BEGIN PRIVATE KEY-----\nabc\n-----END PRIVATE KEY-----",
      GOOGLE_PROJECT_ID: "chs-dashboard-492011",
    } as Env;
    expect(resolveGoogleServiceAccount(full)?.projectId).toBe("chs-dashboard-492011");
    expect(resolveGoogleServiceAccount({ ...full, GOOGLE_PRIVATE_KEY: "" } as Env)).toBeNull();
    expect(resolveGoogleServiceAccount({} as Env)).toBeNull();
  });

  it("imageGenConfigured is false when the toggle is off even if secrets exist", async () => {
    const env = {
      GOOGLE_CLIENT_EMAIL: "sa@example.com",
      GOOGLE_PRIVATE_KEY: "key",
      GOOGLE_PROJECT_ID: "proj",
      DB: {
        prepare: () => ({
          bind: () => ({
            first: async () => ({ value: "false" }),
          }),
        }),
      },
    } as unknown as Env;
    expect(await imageGenConfigured(env)).toBe(false);
  });

  it("imageGenConfigured is true when secrets are present and the toggle is not off", async () => {
    const env = {
      GOOGLE_CLIENT_EMAIL: "sa@example.com",
      GOOGLE_PRIVATE_KEY: "key",
      GOOGLE_PROJECT_ID: "proj",
      DB: {
        prepare: () => ({
          bind: () => ({
            first: async () => ({ value: "true" }),
          }),
        }),
      },
    } as unknown as Env;
    expect(await imageGenConfigured(env)).toBe(true);
  });

  it("resolveImageGenModel reads image_gen_model_id and falls back when the row is missing", async () => {
    const withSetting = {
      DB: {
        prepare: () => ({
          bind: () => ({ first: async () => ({ value: "gemini-3.1-flash-image" }) }),
        }),
      },
    } as unknown as Env;
    expect(await resolveImageGenModel(withSetting)).toBe("gemini-3.1-flash-image");

    const missing = {
      DB: {
        prepare: () => ({
          bind: () => ({ first: async () => null }),
        }),
      },
    } as unknown as Env;
    expect(await resolveImageGenModel(missing)).toBe(IMAGE_GEN_MODEL);
  });

  it("the Vertex URL uses the settings model, not a fixed literal", () => {
    const url = imageGenEndpoint("chs-dashboard-492011", "gemini-3.1-flash-image");
    expect(url).toContain("/models/gemini-3.1-flash-image:generateContent");
    expect(url).not.toContain("imagen-3.0");
    expect(url).not.toContain(":predict");
  });

  it("weekly probe stays quiet on the first failure and notifies once on the second", () => {
    const first = decideImageGenProbe({ status: "ok", streak: 0, notified: false }, false);
    expect(first.notify).toBe(false);
    expect(first.next).toEqual({ status: "fail", streak: 1, notified: false });

    const second = decideImageGenProbe(first.next, false);
    expect(second.notify).toBe(true);
    expect(second.next.streak).toBe(2);
    expect(second.next.notified).toBe(true);

    const third = decideImageGenProbe(second.next, false);
    expect(third.notify).toBe(false);
    expect(third.next.streak).toBe(3);

    const recovered = decideImageGenProbe(third.next, true);
    expect(recovered.notify).toBe(false);
    expect(recovered.next).toEqual({ status: "ok", streak: 0, notified: false });
  });

  it("probe state parses a blank row as none", () => {
    expect(parseProbeState(null)).toEqual({ status: "none", streak: 0, notified: false });
  });

  it("self-test skips non-Mondays and notifies the owner in-app on a second failure", async () => {
    const inserts: string[] = [];
    const env = {
      GOOGLE_CLIENT_EMAIL: "sa@example.com",
      GOOGLE_PRIVATE_KEY: "key",
      GOOGLE_PROJECT_ID: "proj",
      DB: {
        prepare(sql: string) {
          const stmt = {
            bind(key: string) {
              return {
                first: async () => {
                  if (key === "image_gen_enabled") return { value: "true" };
                  if (key === "image_gen_probe_state") {
                    return { value: JSON.stringify({ status: "fail", streak: 1, notified: false }) };
                  }
                  return null;
                },
                run: async () => {
                  inserts.push(sql);
                },
              };
            },
            first: async () => ({
              id: "owner-1",
              email: "tony@homesolutionsar.com",
              first_name: "Tony",
              last_name: null,
              phone: null,
            }),
          };
          return stmt;
        },
      },
    } as unknown as Env;

    const tuesday = new Date(2026, 8, 22);
    const skipped = await runImageGenSelfTest(env, { now: tuesday, generate: async () => {} });
    expect(skipped.ran).toBe(false);

    const monday = new Date(2026, 8, 21);
    const failed = await runImageGenSelfTest(env, {
      now: monday,
      generate: async () => {
        throw new Error("Publisher model was not found");
      },
    });
    expect(failed.ran).toBe(true);
    expect(failed.ok).toBe(false);
    expect(failed.notified).toBe(true);
    expect(inserts.some((sql) => sql.includes("notification_logs"))).toBe(true);
    expect(inserts.some((sql) => sql.includes("Image generation probe"))).toBe(true);
  });
});
