import { describe, expect, it } from "vitest";
import { strToU8, zipSync } from "fflate";
import type { Env } from "../src/env.js";
import { maybeAutoGenerateDocument } from "../src/lib/document-autotrigger.js";
import { handleExpenseCreateJson, handleExpenseUpdate } from "../src/routes/expenses.js";

type ExpenseRow = {
  id: string;
  job_id: string | null;
  amount: number;
  description: string | null;
  incurred_date: string;
  vendor: string | null;
  expense_type: string | null;
  estimate_line_item_id: string | null;
  tax_category: string | null;
  is_1099_reportable: number;
  sub_id: string | null;
  receipt_photo_id: string | null;
  receipt_r2_key: string | null;
  entered_via: string;
  is_active: number;
  created_at: string;
  created_by: string | null;
};

type SubRow = {
  id: string;
  company_name: string;
  worker_type: string | null;
  city_state: string | null;
  trade: string | null;
  phone: string | null;
};

type DocRow = {
  id: string;
  job_id: string;
  template_type: string;
  review_status: string;
  related_record_id: string | null;
  trigger_event: string;
};

const JOB_ID = "job-1";
const USER = {
  id: "user-1",
  email: "tony@example.com",
  first_name: "Tony",
  last_name: "Columbus",
  role: "owner",
  is_active: 1,
};

const templateBytes = zipSync({
  "word/document.xml": strToU8(
    `<?xml version="1.0" encoding="UTF-8" standalone="yes"?>` +
      `<w:document xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main">` +
      `<w:body><w:p><w:r><w:t>{{payment_amount}}</w:t></w:r></w:p></w:body></w:document>`,
  ),
});

function harness() {
  const expenses: ExpenseRow[] = [];
  const subs: SubRow[] = [];
  const docs: DocRow[] = [];
  const dlq: unknown[] = [];
  let lastPutSize = 0;

  const db = {
    prepare(sql: string) {
      return {
        _args: [] as unknown[],
        bind(...args: unknown[]) {
          this._args = args;
          return this;
        },
        async first<T>(): Promise<T | null> {
          const a = this._args;
          if (sql.includes("FROM users WHERE email")) return USER as T;
          if (sql.includes("SELECT id FROM jobs")) {
            return (a[0] === JOB_ID ? { id: JOB_ID } : null) as T;
          }
          if (sql.includes("FROM expenses e")) {
            const exp = expenses.find((e) => e.id === a[0]);
            if (!exp) return null;
            const sub = subs.find((s) => s.id === exp.sub_id);
            return {
              expense_type: exp.expense_type,
              sub_id: exp.sub_id,
              worker_type: sub ? sub.worker_type : null,
            } as T;
          }
          if (sql.includes("SELECT worker_type FROM subcontractors")) {
            const sub = subs.find((s) => s.id === a[0]);
            return (sub ? { worker_type: sub.worker_type } : null) as T;
          }
          if (sql.includes("FROM job_documents")) {
            const jobId = a[0];
            const templateType = a[1];
            const related = sql.includes("related_record_id = ?") ? a[3] : null;
            const hit = docs.find(
              (d) =>
                d.job_id === jobId &&
                d.template_type === templateType &&
                (related == null || d.related_record_id === related) &&
                ["pending_review", "approved", "discarded"].includes(d.review_status),
            );
            return (hit ? { id: hit.id } : null) as T;
          }
          if (sql.includes("job_number") && sql.includes("FROM jobs")) {
            if (a[0] !== JOB_ID) return null;
            return {
              id: JOB_ID,
              job_number: "101",
              title: "Pergola Repair",
              client_id: null,
              property_address: "2511 Lilac",
              property_city: "Conway",
              property_state: "AR",
              property_zip: "72032",
              start_date: null,
              target_end_date: null,
              actual_end_date: null,
              contract_total: 1000,
              deposit_amount: 0,
              notes: null,
              billing_model: "fixed",
              warranty_expiration: null,
              assigned_to: null,
            } as T;
          }
          if (sql.includes("FROM expenses WHERE id")) {
            return (expenses.find((e) => e.id === a[0]) ?? null) as T;
          }
          if (sql.includes("company_name") && sql.includes("FROM subcontractors")) {
            const sub = subs.find((s) => s.id === a[0]);
            return (sub
              ? {
                  company_name: sub.company_name,
                  city_state: sub.city_state,
                  trade: sub.trade,
                  phone: sub.phone,
                }
              : null) as T;
          }
          if (sql.includes("contractor_name")) return null;
          throw new Error(`unhandled first(): ${sql}`);
        },
        async all<T>() {
          if (sql.includes("FROM system_settings")) return { results: [] as T[] };
          throw new Error(`unhandled all(): ${sql}`);
        },
        async run() {
          const a = this._args;
          if (sql.startsWith("INSERT INTO expenses")) {
            expenses.push({
              id: String(a[0]),
              job_id: (a[1] as string | null) ?? null,
              amount: Number(a[2]),
              description: (a[3] as string | null) ?? null,
              incurred_date: String(a[5]),
              vendor: (a[7] as string | null) ?? null,
              expense_type: (a[8] as string | null) ?? null,
              estimate_line_item_id: (a[9] as string | null) ?? null,
              tax_category: (a[10] as string | null) ?? null,
              is_1099_reportable: Number(a[11]),
              sub_id: (a[12] as string | null) ?? null,
              receipt_photo_id: (a[13] as string | null) ?? null,
              receipt_r2_key: (a[14] as string | null) ?? null,
              entered_via: String(a[15]),
              is_active: 1,
              created_at: String(a[16]),
              created_by: (a[17] as string | null) ?? null,
            });
            return;
          }
          if (sql.startsWith("UPDATE expenses SET")) {
            const id = String(a[a.length - 1]);
            const exp = expenses.find((e) => e.id === id);
            if (!exp) throw new Error(`expense missing: ${id}`);
            const setPart = sql.slice("UPDATE expenses SET ".length, sql.indexOf(" WHERE"));
            const cols = setPart.split(",").map((part) => part.trim().split(" ")[0]);
            cols.forEach((col, i) => {
              (exp as unknown as Record<string, unknown>)[col] = a[i];
            });
            return;
          }
          if (sql.startsWith("INSERT INTO job_documents")) {
            docs.push({
              id: String(a[0]),
              job_id: String(a[1]),
              template_type: String(a[2]),
              review_status: "pending_review",
              trigger_event: String(a[5]),
              related_record_id: (a[6] as string | null) ?? null,
            });
            return;
          }
          if (sql.startsWith("INSERT INTO dead_letter_queue")) {
            dlq.push({ payload: a[1], error: a[2] });
            return;
          }
          throw new Error(`unhandled run(): ${sql}`);
        },
      };
    },
  };

  const env = {
    DB: db,
    FILES: {
      async get() {
        const copy = templateBytes.slice();
        return {
          size: copy.byteLength,
          arrayBuffer: async () =>
            copy.buffer.slice(copy.byteOffset, copy.byteOffset + copy.byteLength),
        };
      },
      async put(_key: string, body: ArrayBuffer | Uint8Array) {
        lastPutSize = body.byteLength;
      },
      async head() {
        return { size: lastPutSize };
      },
    },
  } as unknown as Env;

  return { env, expenses, subs, docs, dlq };
}

function ctx() {
  const tasks: Promise<unknown>[] = [];
  return {
    waitUntil(p: Promise<unknown>) {
      tasks.push(p);
    },
    passThroughOnException() {},
    flush: () => Promise.all(tasks),
  };
}

function addSub(
  state: ReturnType<typeof harness>,
  id: string,
  workerType: string | null,
  name: string,
) {
  state.subs.push({
    id,
    company_name: name,
    worker_type: workerType,
    city_state: "Conway, AR",
    trade: workerType === "day_rate_labor" ? "Labor" : "Electrical",
    phone: "501-555-0100",
  });
}

async function postExpense(
  state: ReturnType<typeof harness>,
  body: Record<string, unknown>,
) {
  const c = ctx();
  const res = await handleExpenseCreateJson(
    state.env,
    new Request("https://app.example/api/expenses", {
      method: "POST",
      headers: {
        "content-type": "application/json",
        "Cf-Access-Authenticated-User-Email": USER.email,
      },
      body: JSON.stringify(body),
    }),
    c as unknown as ExecutionContext,
  );
  await c.flush();
  const json = (await res.json()) as { expense?: { id: string } };
  return { status: res.status, id: json.expense?.id ?? null };
}

describe("sub unconditional lien waiver skip", () => {
  it("does not create a waiver for a day-rate worker logged as subcontractor, and the expense still saves", async () => {
    const state = harness();
    addSub(state, "labor-1", "day_rate_labor", "Oscar Linares");

    const created = await postExpense(state, {
      job_id: JOB_ID,
      amount: 150,
      expense_type: "subcontractor",
      sub_id: "labor-1",
      incurred_date: "2026-09-27",
      description: "Day rate",
    });

    expect(created.status).toBe(201);
    expect(created.id).toBeTruthy();
    expect(state.expenses).toHaveLength(1);
    expect(state.docs).toHaveLength(0);
    expect(state.dlq).toHaveLength(0);

    const replay = await maybeAutoGenerateDocument(state.env, {
      jobId: JOB_ID,
      templateType: "lien_waiver_sub_unconditional",
      triggerEvent: "sub_payment",
      relatedRecordId: created.id,
      overrides: { sub_id: "labor-1", payment_amount: "150", payment_date: "2026-09-27" },
    });
    expect(replay).toEqual({ generated: false, reason: "day_rate_labor" });
    expect(state.docs).toHaveLength(0);
    expect(state.dlq).toHaveLength(0);
  });

  it("does not create a waiver for a day-rate worker logged as labor, even if the generator is invoked", async () => {
    const state = harness();
    addSub(state, "labor-1", "day_rate_labor", "Oscar Linares");

    const created = await postExpense(state, {
      job_id: JOB_ID,
      amount: 150,
      expense_type: "labor",
      sub_id: "labor-1",
      incurred_date: "2026-09-27",
    });

    expect(created.status).toBe(201);
    expect(state.expenses).toHaveLength(1);
    expect(state.docs).toHaveLength(0);
    expect(state.dlq).toHaveLength(0);

    const direct = await maybeAutoGenerateDocument(state.env, {
      jobId: JOB_ID,
      templateType: "lien_waiver_sub_unconditional",
      triggerEvent: "sub_payment",
      relatedRecordId: created.id,
      overrides: { sub_id: "labor-1", payment_amount: "150", payment_date: "2026-09-27" },
    });
    expect(direct).toEqual({ generated: false, reason: "day_rate_labor" });
    expect(state.docs).toHaveLength(0);
    expect(state.dlq).toHaveLength(0);
  });

  it("skips expense_type labor even when the linked person is a true subcontractor", async () => {
    const state = harness();
    addSub(state, "sub-1", "subcontractor", "Ace Electric");
    state.expenses.push({
      id: "exp-labor",
      job_id: JOB_ID,
      amount: 200,
      description: null,
      incurred_date: "2026-09-27",
      vendor: null,
      expense_type: "labor",
      estimate_line_item_id: null,
      tax_category: null,
      is_1099_reportable: 0,
      sub_id: "sub-1",
      receipt_photo_id: null,
      receipt_r2_key: null,
      entered_via: "web",
      is_active: 1,
      created_at: "2026-09-27",
      created_by: USER.email,
    });

    const result = await maybeAutoGenerateDocument(state.env, {
      jobId: JOB_ID,
      templateType: "lien_waiver_sub_unconditional",
      triggerEvent: "sub_payment",
      relatedRecordId: "exp-labor",
      overrides: { sub_id: "sub-1", payment_amount: "200", payment_date: "2026-09-27" },
    });
    expect(result).toEqual({ generated: false, reason: "day_rate_labor" });
    expect(state.docs).toHaveLength(0);
    expect(state.dlq).toHaveLength(0);
  });

  it("creates exactly one pending waiver for a true subcontractor, and an edit or replay does not add another", async () => {
    const state = harness();
    addSub(state, "sub-1", "subcontractor", "Ace Electric");

    const created = await postExpense(state, {
      job_id: JOB_ID,
      amount: 800,
      expense_type: "subcontractor",
      sub_id: "sub-1",
      incurred_date: "2026-09-27",
      vendor: "Ace Electric",
    });
    expect(created.status).toBe(201);
    expect(state.docs).toHaveLength(1);
    expect(state.docs[0].review_status).toBe("pending_review");
    expect(state.docs[0].related_record_id).toBe(created.id);
    expect(state.docs[0].template_type).toBe("lien_waiver_sub_unconditional");
    expect(state.dlq).toHaveLength(0);

    const updated = await handleExpenseUpdate(
      state.env,
      new Request("https://app.example/api/expenses/" + created.id, {
        method: "PUT",
        headers: {
          "content-type": "application/json",
          "Cf-Access-Authenticated-User-Email": USER.email,
        },
        body: JSON.stringify({ amount: 900, incurred_date: "2026-10-01" }),
      }),
      created.id!,
    );
    expect(updated.status).toBe(200);
    expect(state.expenses[0].amount).toBe(900);
    expect(state.expenses[0].incurred_date).toBe("2026-10-01");
    expect(state.docs).toHaveLength(1);

    const replay = await maybeAutoGenerateDocument(state.env, {
      jobId: JOB_ID,
      templateType: "lien_waiver_sub_unconditional",
      triggerEvent: "sub_payment",
      relatedRecordId: created.id,
      overrides: { sub_id: "sub-1", payment_amount: "900", payment_date: "2026-10-01" },
    });
    expect(replay).toEqual({ generated: false, reason: "already_exists" });
    expect(state.docs).toHaveLength(1);
    expect(state.dlq).toHaveLength(0);
  });

  it("treats a NULL worker_type as a true subcontractor and creates one waiver", async () => {
    const state = harness();
    addSub(state, "sub-legacy", null, "Legacy Electric");

    const created = await postExpense(state, {
      job_id: JOB_ID,
      amount: 400,
      expense_type: "subcontractor",
      sub_id: "sub-legacy",
      incurred_date: "2026-09-27",
    });

    expect(created.status).toBe(201);
    expect(state.docs).toHaveLength(1);
    expect(state.docs[0].review_status).toBe("pending_review");
    expect(state.docs[0].related_record_id).toBe(created.id);
    expect(state.dlq).toHaveLength(0);
  });
});
