-- Sprint 38 Run 2: AI-Generated Weekly Client Text Recap
--
-- Updates the weekly_photo_summary email template to include a {{weekly_recap}}
-- merge field slot. The recap paragraph is generated by generateWeeklyRecap()
-- in src/lib/weekly-recap.ts and passed as a merge field via triggerNotification.
-- Falls back to an empty string if Claude is unavailable, preserving the
-- existing photo-link behavior without change.

UPDATE notification_templates
SET body_template = '{{weekly_recap}}

See this week''s photos and project updates: {{photo_summary_link}}',
    updated_at = datetime('now')
WHERE id = 'nt-weekly-photo-summary-email';
